archlinux/PKGBUILD
=> fix(PKGBUILD): remove unused deepin-daemon dependency

debian/rules
Log: https://github.com/orgs/linuxdeepin/discussions/4301
=> feat: enable default hardening for deb

CMakeLists.txt, debian/changelog
Changelog:
* add hover state for AppListView items (https://github.com/linuxdeepin/developer-center/issues/6205)
* fix incorrect icon size when using HiDPI (https://github.com/linuxdeepin/developer-center/issues/6137)
Log:
=> chore: release dde-launchpad 0.2.2

translations/dde-launchpad.ts, translations/dde-launchpad_az.ts, translations/dde-launchpad_bo.ts, translations/dde-launchpad_ca.ts, translations/dde-launchpad_es.ts, translations/dde-launchpad_fi.ts, translations/dde-launchpad_fr.ts, translations/dde-launchpad_hu.ts, translations/dde-launchpad_it.ts, translations/dde-launchpad_ja.ts, translations/dde-launchpad_ko.ts, translations/dde-launchpad_nb_NO.ts, translations/dde-launchpad_pl.ts, translations/dde-launchpad_pt_BR.ts, translations/dde-launchpad_ru.ts, translations/dde-launchpad_uk.ts, translations/dde-launchpad_zh_CN.ts, translations/dde-launchpad_zh_HK.ts, translations/dde-launchpad_zh_TW.ts
=> chore(i18n): update ts files

qml/AppItemMenu.qml
when launcher is invisible, close and desory menu created
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/6716
=> fix: menu do not auto hide when launcher invisible

qml/Main.qml
when window visible changed, request window activate
log: make window activated when shown
=> fix: launchpad can not get input focus when second show

.reuse/dep5, docs/DConfig.md, src/models/CMakeLists.txt, src/models/appsmodel.cpp, src/models/appsmodel.h, src/models/org.deepin.dde.launchpad.appsmodel.json
添加配置项，允许配置默认排除显示的应用列表。
相关 https://github.com/linuxdeepin/developer-center/issues/6650
=> feat: add config to specific exclude app list

qml/AppListView.qml, qml/GridViewContainer.qml
Always scroll to the highlight when focus in.
Log: fix all apps and favorite apps highlight focus
Issue: https://github.com/linuxdeepin/developer-center/issues/6397
=> fix: all apps and favorite apps highlight focus

qml/Main.qml
set minimumWidth and minimumHeight to dialog
Issue: https://github.com/linuxdeepin/developer-center/issues/6687
=> fix: The issue about uninstall dialog's height

CMakeLists.txt, debian/control, main.cpp
This reverts commit 7589e73198562fa7e02b65411e7d744a5fd00156.
=> Revert "fix: existing wm titlebar"

qml/AppItemMenu.qml
correct the typo
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/6716
=> fix: wrong property name

qml/Main.qml
This reverts commit cc750bc5e66bb219a2f2b37e72ed380193684c35.
=> Revert "fix: full screen always dark theme"

qml/AppItemMenu.qml
using appItem's icon.
Issue: https://github.com/linuxdeepin/developer-center/issues/6686
=> fix: missing icon for uninstall

CMakeLists.txt, debian/changelog
* Adjust section title font size in WindowedFrame (https://github.com/linuxdeepin/developer-center/issues/6208)
* Fix context menu did not get hide (https://github.com/linuxdeepin/developer-center/issues/6716)
* Make icon DnD in FullscreenFrame easier (https://github.com/linuxdeepin/developer-center/issues/6286)
* Allow Shift+Alphabetic key to quick search (https://github.com/linuxdeepin/developer-center/issues/6859)
* Fix missing icon for uninstall (https://github.com/linuxdeepin/developer-center/issues/6686)
* Update page indicator when page count changed (https://github.com/linuxdeepin/developer-center/issues/6861)
=> chore: release dde-launchpad 0.4.2

qml/FullscreenFrame.qml
Enabled option to make a clip when there are more apps in a group and it has a second page
=> Enabled option to make a clip

main.cpp
add file and journal appender for log.
=> feat: add log appender

qml/AppListView.qml, qml/GridViewContainer.qml
Use positionViewAtIndex instead. Also modify focus policy to move
to current index when focus in.
Log: fix sometimes scroll failed
Issue: https://github.com/linuxdeepin/developer-center/issues/6897
=> fix: sometimes scroll failed

qml/AppItemMenu.qml, qml/Main.qml
`appItem` is released in sometimes, which is an invalid value.
Issue: https://github.com/linuxdeepin/developer-center/issues/6945
=> fix: Type error when uninstall app

systemd/CMakeLists.txt, systemd/org.deepin.dde.Launcher1.service.in
move service to session.slice
Log:
=> chore: update systemd service

qml/FullscreenFrame.qml, qml/WindowedFrame.qml, src/quick/launcherappiconprovider.cpp
Adding iconTheme to it's url, `QQuickImageBase` has a cache store,
and Url as a part of the key.
=> fix: icon doesn't change when iconTheme changed

qml/FullscreenFrame.qml, qml/WindowedFrame.qml
Issues: linuxdeepin/developer-center#6373
=> fix: unable to trigger search through numeric keys

qml/IconItemDelegate.qml
Issues: linuxdeepin/developer-center#6372
=> chore: app name label add horizontal padding

qml/WindowedFrame.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/6156 Log:
=> fix: return to mainview when click keyboard

qml/AppListView.qml, qml/FullscreenFrame.qml, qml/IconItemDelegate.qml, qml/Main.qml, qml/WindowedFrame.qml, src/quick/launcherappiconprovider.cpp, src/quick/launcherfoldericonprovider.cpp
=> fix: adjust style

CMakeLists.txt, archlinux/PKGBUILD
=> chore: drop Qt5 build support

qml/FullscreenFrame.qml, src/models/itemspage.cpp, src/models/multipageproxymodel.cpp, src/models/multipageproxymodel.h
auto remove invalid pages when app uninstalled
Log:
Issues: linuxdeepin/developer-center#5625
=> fix: auto remove invalid pages

src/ddeintegration/CMakeLists.txt, src/ddeintegration/appmgr.cpp, src/ddeintegration/appmgr.h, src/ddeintegration/types/amglobaltypes.h, src/ddeintegration/types/objectmap.h, src/ddeintegration/types/propmap.h, src/ddeintegration/types/qstringmap.h, src/ddeintegration/xml/org.desktopspec.ApplicationManager1.Application.xml, src/ddeintegration/xml/org.desktopspec.ObjectManager1.xml, src/models/CMakeLists.txt, src/models/appsmodel.cpp, src/models/appsmodel.h
=> feat: replacing gio with AM

src/quick/launcherfoldericonprovider.cpp, src/utils/iconutils.cpp, src/utils/iconutils.h
icon is png and it's icon size is not in perfectIconSize.
=> fix: folder icon is blur

main.cpp, src/ddeintegration/appmgr.cpp, src/ddeintegration/appmgr.h, src/models/CMakeLists.txt, src/models/appitem.cpp, src/models/appitem.h, src/models/appsmodel.cpp, src/models/countlimitproxymodel.cpp, src/models/countlimitproxymodel.h, src/models/recentlyinstalledproxymodel.cpp, src/models/recentlyinstalledproxymodel.h
Adding CountLimitProxyModel to limit Model's count.
Adding recently installed model.
=> feat: add recently installed model

qml/windowed/AppListView.qml, src/models/appitem.h, src/models/appsmodel.h, src/models/categorizedsortproxymodel.cpp, src/models/categorizedsortproxymodel.h
add DDE category function according to the new design.
Log: add DDE category style
Influence: DDE category
=> feat: add DDE category style

src/ddeintegration/appmgr.cpp, src/ddeintegration/appmgr.h, src/models/appsmodel.cpp, src/models/appsmodel.h
=>  feat: updating AppItem when App property changed

debian/control, qml/windowed/SideBar.qml
=> fix: add miss dependency

src/ddeintegration/appmgr.cpp, src/ddeintegration/appmgr.h, src/ddeintegration/xml/org.desktopspec.ApplicationManager1.Application.xml, src/models/appitem.cpp, src/models/appitem.h, src/models/appsmodel.cpp, src/models/recentlyinstalledproxymodel.cpp, src/models/searchfilterproxymodel.cpp, src/models/searchfilterproxymodel.h
Ordering by launchpad times for allApps.
=> feat: order by launched times

CMakeLists.txt, debughelper.h, desktopintegration.h, launchercontroller.h, main.cpp, qml/AppItemMenu.qml, qml/DebugDialog.qml, qml/FullscreenFrame.qml, qml/IconItemDelegate.qml, qml/Main.qml, qml/WindowedFrame.qml, qml/windowed/AlphabetCategoryPopup.qml, qml/windowed/AppList.qml, qml/windowed/AppListView.qml, qml/windowed/SideBar.qml, src/models/CMakeLists.txt, src/models/appitem.h, src/models/appsmodel.h, src/models/categorizedsortproxymodel.h, src/models/countlimitproxymodel.h, src/models/favoritedproxymodel.h, src/models/multipageproxymodel.h, src/models/multipagesortfilterproxymodel.h, src/models/recentlyinstalledproxymodel.h, src/models/searchfilterproxymodel.h
Using QML_NAMED_ELEMENT to register qml types.
Using static module to manage quick modules.
=> feat: using qt6 syntax to manage quick module

qml/WindowedFrame.qml
Add SearchEdit with no background color when not activated in small window mode
Log: SearchEdit with no background color
Influence: window mode
=> feat: SearchEdit with no background color

qml/windowed/SideBar.qml
update focus policy of SideBar
Log:
=> feat: update focus policy of SideBar

qml/FullscreenFrame.qml, qml/GridViewContainer.qml, qml/IconItemDelegate.qml, qml/WindowedFrame.qml, qml/windowed/AlphabetCategoryPopup.qml
Adjust the display effect of the GridViewContainer Adjust the icon dragging in full-screen mode
Log: Adjust the display effect of the GridViewContainer
Influence: fullscreen mode
=> feat: Adjust the display effect of the GridViewContainer

qml/WindowedFrame.qml, qml/windowed/SideBar.qml
modification:margins, seperatorline width, alignment
Log:
=> feat: modify ui

src/models/recentlyinstalledproxymodel.cpp
=> fix: removing time limits for recently installed model

src/ddeintegration/appmgr.cpp
fallback to Name for deepin application.
=> fix: wrong displayName when Property changed

debian/control
add build Build-Depends for 3b6e24
log:
=> fix: build error

qml/GridViewContainer.qml
It causes app can't be launched. revert to early calculation method.
=> fix: wrong cell size

debian/control, src/utils/CMakeLists.txt, src/utils/iconutils.cpp
Replacing QIconLoader with QIcon to update cache.
=> chore: avoid to using GuiPrivate module

qml/WindowedFrame.qml, src/models/countlimitproxymodel.cpp, src/models/countlimitproxymodel.h, src/models/searchfilterproxymodel.cpp, src/models/searchfilterproxymodel.h
Filtering apps from the recently installed list.
=> feat: filtering recently installed app for allAppsModel

CMakeLists.txt, qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml, qml/windowed/AppList.qml, qml/windowed/AppListView.qml, qml/windowed/CMakeLists.txt, qml/windowed/FreeSortListView.qml, qml/windowed/SideBar.qml, qml/windowed/WindowedFrame.qml, src/models/CMakeLists.txt, src/models/freesortproxymodel.cpp, src/models/freesortproxymodel.h, src/models/itemarrangementproxymodel.cpp, src/models/itemarrangementproxymodel.h, src/models/itemspage.cpp, src/models/itemspage.h, src/models/multipagesortfilterproxymodel.cpp
add app listview free sort function for new design
Log: add app listview free sort function
Influence: app listview free sort
=> feat: add app listview free sort function

qml/windowed/CMakeLists.txt, qml/windowed/GridViewContainer.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/WindowedFrame.qml
=> feat: adapt to v25 UI for recentlyinstalled

debian/control
=> chore: add dependency on dde-application-manager

CMakeLists.txt, qml/DebugBounding.qml, qml/GridViewContainer.qml, qml/windowed/AnalysisView.qml, qml/windowed/BottomBar.qml, qml/windowed/CMakeLists.txt, qml/windowed/FrequentlyUsedView.qml, qml/windowed/GridViewContainer.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/RecentlyInstalledView.qml, qml/windowed/WindowedFrame.qml
For the convenience of debugging and expansion.
=> refact: split windowed view

qml/windowed/AnalysisView.qml, src/models/recentlyinstalledproxymodel.cpp, src/models/recentlyinstalledproxymodel.h
=> fix: removing warning

debughelper.cpp, debughelper.h, qml/DebugBounding.qml, qml/DebugDialog.qml, qml/Helper.qml, qml/Main.qml, qml/windowed/AnalysisView.qml, qml/windowed/AppList.qml, qml/windowed/BottomBar.qml, qml/windowed/GridViewContainer.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/RecentlyInstalledView.qml, qml/windowed/SideBar.qml, qml/windowed/WindowedFrame.qml
=> feat: adjust windowed's ui size

qml/AppItemMenu.qml, qml/Helper.qml, qml/Main.qml, qml/windowed/AnalysisView.qml, qml/windowed/FrequentlyUsedView.qml, qml/windowed/GridViewContainer.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/RecentlyInstalledView.qml, qml/windowed/WindowedFrame.qml, translations/dde-launchpad.ts, translations/dde-launchpad_az.ts, translations/dde-launchpad_bo.ts, translations/dde-launchpad_ca.ts, translations/dde-launchpad_es.ts, translations/dde-launchpad_fi.ts, translations/dde-launchpad_fr.ts, translations/dde-launchpad_hu.ts, translations/dde-launchpad_it.ts, translations/dde-launchpad_ja.ts, translations/dde-launchpad_ko.ts, translations/dde-launchpad_nb_NO.ts, translations/dde-launchpad_pl.ts, translations/dde-launchpad_pt_BR.ts, translations/dde-launchpad_ru.ts, translations/dde-launchpad_uk.ts, translations/dde-launchpad_zh_CN.ts, translations/dde-launchpad_zh_HK.ts, translations/dde-launchpad_zh_TW.ts
Reverting scrollbar and Keys.
Removing some warning.
=> feat: missing function for searching view

desktopintegration.cpp, desktopintegration.h, qml/Main.qml, src/ddeintegration/appearance.cpp, src/ddeintegration/appearance.h
=> feat: windowed'transparency follows changes

CMakeLists.txt, qml/windowed/AnalysisView.qml, qml/windowed/CMakeLists.txt, qml/windowed/FrequentlyUsedView.qml, qml/windowed/SearchResultView.qml, qml/windowed/WindowedFrame.qml, src/models/CMakeLists.txt, src/models/frequentlyusedproxymodel.cpp, src/models/frequentlyusedproxymodel.h, src/models/searchfilterproxymodel.cpp, src/models/searchfilterproxymodel.h, translations/dde-launchpad.ts, translations/dde-launchpad_az.ts, translations/dde-launchpad_bo.ts, translations/dde-launchpad_ca.ts, translations/dde-launchpad_es.ts, translations/dde-launchpad_fi.ts, translations/dde-launchpad_fr.ts, translations/dde-launchpad_hu.ts, translations/dde-launchpad_it.ts, translations/dde-launchpad_ja.ts, translations/dde-launchpad_ko.ts, translations/dde-launchpad_nb_NO.ts, translations/dde-launchpad_pl.ts, translations/dde-launchpad_pt_BR.ts, translations/dde-launchpad_ru.ts, translations/dde-launchpad_uk.ts, translations/dde-launchpad_zh_CN.ts, translations/dde-launchpad_zh_HK.ts, translations/dde-launchpad_zh_TW.ts
Splitting search's view and model.
=> refact: split search and frequentlyUsed proxymodel

qml/windowed/FreeSortListView.qml, src/models/freesortproxymodel.cpp
move item position in appListView free sorting mode
Log: move item position in appListView free sorting mode
Influence: app listview move item position
=> feat: move item position in appListView free sorting mode

qml/FullscreenFrame.qml, qml/windowed/BottomBar.qml
=> feat: removing searchText's whitespace from the start and the end

qml/windowed/AnalysisView.qml, qml/windowed/FrequentlyUsedView.qml, qml/windowed/SearchResultView.qml, qml/windowed/WindowedFrame.qml
小窗口启动器，搜索框中按上/下/回车时，激活右侧应用区域的焦点。
Log:
=> feat: key navigation for windowed frame search edit

qml/FullscreenFrame.qml, qml/GridViewContainer.qml
The default selected app when flipping up has not been handled to be the last app.
Add processing code
Issue: https://github.com/linuxdeepin/developer-center/issues/7578
Issue: https://github.com/linuxdeepin/developer-center/issues/7580
=> fix: Handling exceptions when flipping up.

qml/windowed/AlphabetCategoryPopup.qml, qml/windowed/AppListView.qml, qml/windowed/GridViewContainer.qml, src/models/categorizedsortproxymodel.cpp
modify alphabet category popup style for new design
Log: modify alphabet category popup style
Influence: alphabet category popup display
=> chore: modify alphabet category popup style

qml/AppItemMenu.qml, qml/FullscreenFrame.qml, qml/Main.qml
fix not close the menu when turning pages if the menu is showing
Log: close the menu when turning pages
Influence: close the menu when turning pages
Issus: https://github.com/linuxdeepin/developer-center/issues/7646
=> fix: close the menu when turning pages

qml/windowed/WindowedFrame.qml
小窗口界面，点击空白位置时，移除焦点（实际是将焦点置于根节点组件）。
Issue: https://github.com/linuxdeepin/developer-center/issues/7638
=> fix: allow click empty area to remove focus

qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml
Fix the problem that the space key or enter key cannot open the app
Log: fix space key or enter key cannot open the app
Issues: https://github.com/linuxdeepin/developer-center/issues/7643
Influence: pace key or enter key can open the app
=> fix: space key or enter key cannot open the app

qml/windowed/FreeSortListView.qml
There is no icon or the image is displayed incorrectly when dragging an item. There is no such problem when handling in mouseArea.
Log: fix drag item has no icon or error icon
Issues: https://github.com/linuxdeepin/developer-center/issues/7636
Influence: drag item icon
=> fix: drag item has no icon or error icon

src/models/recentlyinstalledproxymodel.cpp
incorect type cast from long long to int.
=> fix: missing recently time module

debian/control
=> chore: update dependency for dde-application-manager

CMakeLists.txt
=> refact: using absolute paths in cmake

qml/FullscreenFrame.qml
optimize the logic of dragging item to create new page
Log: optimize the logic of dragging item to create new page
Influence: dragging item to create new page
=> chore: optimize the logic of dragging item to create new page

src/models/itemarrangementproxymodel.cpp, src/models/itemspage.cpp, src/models/itemspage.h
Drag and drop the item onto the page, but it is not inserted in current page.
Log: fix dropping item onto page but not insert in current page
Influence: drop item onto page
=> fix: drop item onto page but not insert in current page

qml/windowed/BottomBar.qml
Modify the SearchEdit style in window mode and add a hover effect.
Log:
Influence:
=> fix: Modify the SearchEdit style in window mode and add a hover effect.

qml/Helper.qml, qml/windowed/FreeSortListView.qml, qml/windowed/WindowedFrame.qml
add left and right margin
Issue: https://github.com/linuxdeepin/developer-center/issues/7779
Issue: https://github.com/linuxdeepin/developer-center/issues/7778
=> fix: applist margin

debian/control, desktopintegration.cpp, desktopintegration.h, qml/AppItemMenu.qml, src/ddeintegration/appmgr.cpp, src/ddeintegration/appmgr.h, src/ddeintegration/xml/org.desktopspec.ApplicationManager1.Application.xml
Disabling scale by env instead of scaleFactor, and it's removed
in AM.
Issue: https://github.com/linuxdeepin/developer-center/issues/7733
=> refact: disable scale for app

qml/FullscreenFrame.qml
don't need to set placeholder text
Issue: https://github.com/linuxdeepin/developer-center/issues/7625
=> fix: english text for search edit

qml/windowed/SideBar.qml, qml/windowed/WindowedFrame.qml
use anchors to relayout.
Issue: https://github.com/linuxdeepin/developer-center/issues/7785
=> fix: nav not align vcenter to window

.reuse/dep5, CMakeLists.txt, dde-shell-wrapper/main.cpp, dde-shell-wrapper/package/main.qml, dde-shell-wrapper/package/metadata.json, dde-shell-wrapper/src.cmake, debian/control, qml/Main.qml
dde-shell loads org.deepin.ds.launchpad.
e.g:
```
export DDE_SHELL_PACKAGE_PATH=/src-path/build/packages
export DDE_SHELL_PLUGIN_PATH=/src-path/build/plugins
dde-shell -p org.deepin.ds.launchpad
```
Issue: https://github.com/linuxdeepin/developer-center/issues/5810
=> feat: add dde-shell-wrapper

qml/windowed/AppListView.qml
Log: Adapt to dark mode
Issue: https://github.com/linuxdeepin/developer-center/issues/7783
=> fix: Some text is not adapted to dark mode

tests/itemspagetest.cpp
add unit test for dragging item to folder
Log: add unit test for dragging item to folder
Influence: none
=> feat: add unit test for dragging item to folder

qml/windowed/WindowedFrame.qml
log: linuxdeepin/developer-center#7787
=> fix: error color of splitLine in dark mode

qml/GridViewContainer.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/7837
Log: FocusBox area didn't fit IconItem
=> fix: FocusBox area didn't fit IconItem

qml/windowed/FreeSortListView.qml
In the case of freely sorting listview, drag the item to move the position and provide position indication and group indication functions.
Log: added drag item indicator function
Influence: drag item indicator function
=> feat: added drag item indicator function

qml/windowed/AnalysisView.qml, qml/windowed/AppList.qml, qml/windowed/BottomBar.qml, qml/windowed/FreeSortListView.qml, qml/windowed/FrequentlyUsedView.qml, qml/windowed/GridViewContainer.qml, qml/windowed/RecentlyInstalledView.qml, qml/windowed/SearchResultView.qml, qml/windowed/SideBar.qml, qml/windowed/WindowedFrame.qml
Modify focus chain order according to design
Log: modify launchpad tab focus chain order
Influence: tab focus chain order
=> fix: modify launchpad tab focus chain order

qml/windowed/WindowedFrame.qml
* remove duplicate unused id.
* remove conflicting layout policy, use newer one.
Log: remove some duplicate statements
=> chore: remove some duplicate statements

qml/FullscreenFrame.qml
set the padding of item to 0 from 5 px
Issue: https://github.com/linuxdeepin/developer-center/issues/7634
=> fix: text item is abnormal at dpi 2.0

dde-shell-wrapper/main.cpp, main.cpp, qml/windowed/AppList.qml, qml/windowed/SideBar.qml, src/models/categorizedsortproxymodel.cpp, src/models/categorizedsortproxymodel.h, src/models/org.deepin.dde.launchpad.appsmodel.json
Store App sort type in configs.
Issue: https://github.com/linuxdeepin/developer-center/issues/7652
Log: App sort type was not persistent
=> fix: App sort type was not persistent

qml/AppItemMenu.qml
=> fix: tmp disable send2dock for app group

qml/AppItemMenu.qml
it's maybe need to be deleted.
=> fix: eating Tab for invisible MenuItem

qml/windowed/AppListView.qml
Modify the styling of listview titles in category mode.
Issue: https://github.com/linuxdeepin/developer-center/issues/7938
=> fix spacing issue between title and content in category mode

qml/FullscreenFrame.qml, qml/GridViewContainer.qml, src/models/itemarrangementproxymodel.cpp
应设计要求，全屏格子数量调整为 4 * 8，左右留白调整为 0.5 个格子。
Issue: linuxdeepin/developer-center#7987
Log:
=> feat: now fullscreen grid is 4 * 8

qml/FolderGridViewPopup.qml, qml/GridViewContainer.qml, qml/windowed/AlphabetCategoryPopup.qml, qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml, qml/windowed/GridViewContainer.qml
Item has itself palette in qt6.
=> refact: using QuickItem's palette instead of SystemPalette

qml/windowed/BottomBar.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/7942
需要 https://github.com/linuxdeepin/dtkdeclarative/pull/316 才能生效
=> feat: use the bright text in search editer

qml/FullscreenFrame.qml, qml/IconItemDelegate.qml
Let drag start after 300ms long press.
Log: fix swipe and drag conflicts
Issue: https://github.com/linuxdeepin/developer-center/issues/6359
=> fix: swipe and drag conflicts

qml/windowed/FreeSortListView.qml
fix: No background color needed during drag.
Remove background during drag.
Issue: https://github.com/linuxdeepin/developer-center/issues/7944
log: as title
=> fix: No background color needed during drag.

qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml
log: https://github.com/linuxdeepin/developer-center/issues/7940
=> feat: use bright text color for app name

qml/windowed/WindowedFrame.qml
Adjust the splitter style of the launcher.
Issue: https://github.com/linuxdeepin/developer-center/issues/7930
log: as title
=> fix: Adjust the splitter style of the launcher.

qml/windowed/FreeSortListView.qml
=> Adjust the position of the dropIndicator

qml/windowed/AppListView.qml, qml/windowed/BottomBar.qml, qml/windowed/SideBar.qml, qml/windowed/WindowedFrame.qml
=> chore: bottombar style

qml/Main.qml, qml/windowed/WindowedFrame.qml
Replacing left align with center align.
=> fix: launchpad's left align

qml/windowed/AppListView.qml, qml/windowed/CMakeLists.txt, qml/windowed/FreeSortListView.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/ItemBackground.qml, qml/windowed/SideBar.qml
log: https://github.com/linuxdeepin/developer-center/issues/7935
=> fix: use more lighter background for item

qml/windowed/BottomBar.qml
log: missing change in
https://github.com/linuxdeepin/dde-launchpad/pull/208
=> fix: missing background set for shutdown/fullscreen button

qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml
=> fix: warning binding loop detected for windowText

src/models/org.deepin.dde.launchpad.appsmodel.json
使用 FreeCategory（值为 2）作为列表默认类别的默认配置。
Issue: linuxdeepin/developer-center#8022
Log:
=> fix: categoryType default to freeform sorting

qml/Main.qml, src/ddeintegration/ddedock.cpp
as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/8072
=> fix: incorrect position firstly

CMakeLists.txt, debian/changelog, qml/AppItemMenu.qml, src/models/itemarrangementproxymodel.cpp
* fix config file location (linuxdeepin/developer-center#8096)
* hide "add to favorite" menu (linuxdeepin/developer-center#8086)
=> dde-launchpad: release 0.6.5

CMakeLists.txt, debian/changelog, qml/windowed/AppListView.qml, qml/windowed/BottomBar.qml, qml/windowed/FreeSortListView.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/ItemBackground.qml, qml/windowed/SideBar.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/8135
=> fix: missing focus box border for some items

qml/FullscreenFrame.qml, qml/IconItemDelegate.qml, qml/windowed/IconItemDelegate.qml
根据 shule 的要求作出对应的 UI 调整。包括全屏状态下 item 的间距与翻页标识在应用文件夹被打开时的透明度。
=> chore: UI tweaks according to designer

qml/FullscreenFrame.qml, qml/windowed/FreeSortListView.qml
使用 DropArea 的 keys 属性检查 MIME 类型。
Log:
=> chore: make use of DropArea's keys property

qml/windowed/BottomBar.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/8182
=> fix: use more bright color for search icon

qml/windowed/AppList.qml, qml/windowed/AppListView.qml
Issue: linuxdeepin/developer-center#8135
=> fix: error keytab target for category list view

qml/FullscreenFrame.qml
Log: https://github.com/linuxdeepin/developer-center/issues/8182 全屏保持一致
=> chore: also set bright color for search icon in fullscreen

qml/FullscreenFrame.qml
应 shule 设计要求，禁用全屏模式下首尾页滚动。
目前的交互效果与设计预期不符，期望的效果目前不好实现。
Log:
=> fix: disable page wrap in fullscreen frame

debian/control, qml/FolderGridViewPopup.qml, qml/windowed/AlphabetCategoryPopup.qml, qml/windowed/AppListView.qml
Using dtk's Control.
Removing categroy and alphabet's drop shadow.
=> fix: lower blur's radius for FolderPopup

src/models/itemarrangementproxymodel.cpp
The configuration save path is also incorrect.
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8370
=> fix: The full-screen configuration is reset.

qml/windowed/FreeSortListView.qml
Block the folder context menu.
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8403
=> fix: The folder has a context menu.

qml/FolderGridViewPopup.qml
Application group name TextInput supports mouse selection
Log:
=> feat: Application group name TextInput supports mouse selection

qml/FolderGridViewPopup.qml
can not set empty name
Issue: https://github.com/linuxdeepin/developer-center/issues/8334
=> fix: application groups can set empty name

qml/IconItemDelegate.qml, qml/Main.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/SideBar.qml, qml/windowed/WindowedFrame.qml
set windowRadius to 12.
sidebar's topMargin is equal width leftMargin.
Issue: https://github.com/linuxdeepin/developer-center/issues/8409
=> fix: adjust ui

qml/FullscreenFrame.qml, qml/windowed/GridViewContainer.qml, qml/windowed/SearchResultView.qml
search result view show vertical scrollbar
Log: search result view show vertical scrollbar
Issue: https://github.com/linuxdeepin/developer-center/issues/7833
Influence: search result view show vertical scrollbar
=> fix: search result view show vertical scrollbar

qml/windowed/IconItemDelegate.qml
Increase top padding and decrease bottom padding according to designer.
Log: adjust icon top and bottom padding
=> chore: adjust icon top and bottom padding

qml/FullscreenFrame.qml, qml/windowed/WindowedFrame.qml
The combination keys have not been blocked.
Issue: https://github.com/linuxdeepin/developer-center/issues/8463
=> fix: The search box input text is not responsive.

qml/FolderGridViewPopup.qml, qml/IconItemDelegate.qml, qml/windowed/WindowedFrame.qml
- fix cannot click on app in folder
- fix text overflow in folder grid view
=> fix: folder grid view

qml/windowed/GridViewContainer.qml
=> fix: search result overflow

qml/FullscreenFrame.qml, qml/GridViewContainer.qml
全屏模式始终显示高亮项。用户始终会知道搜索过程中按下回车会启动哪个
应用。
Log:
=> feat: always show highlighted item on FullscreenFrame

qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml, qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml, qml/windowed/FrequentlyUsedView.qml, qml/windowed/RecentlyInstalledView.qml, qml/windowed/SearchResultView.qml
focus to baseLayer after menu popup
Issue: https://github.com/linuxdeepin/developer-center/issues/7629
=> fix: searchEdit focus not changed after menu popup

qml/Main.qml
Issues: linuxdeepin/developer-center#8860
=> fix: when compositing turned off a rounded corner border appears inside the window

debian/changelog, qml/AppItemMenu.qml, qml/FullscreenFrame.qml, qml/GridViewContainer.qml, qml/Main.qml, qml/windowed/FreeSortListView.qml, src/models/itemarrangementproxymodel.cpp, src/models/itemarrangementproxymodel.h
切分支重新打 tag，删除 0.6.12 以来的 feat
* fix: folder did not remove without item (linuxdeepin/developer-center#8947)
* Fix #8577
* Fix #8862
* Fix #8376
* Fix #8689
* Fix #8244
* Fix #8384
* release 0.7.1
=> chore: bump version to 0.7.1

src/models/appsmodel.cpp
The refresh slot function was not successfully connected
Issue: https://github.com/linuxdeepin/developer-center/issues/8968
=> fix: launcher application item not updating

qml/FullscreenFrame.qml
only highlight in search result gridview
=> chore: only highlight item in searchResultGridView

qml/FolderGridViewPopup.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/7949
Log: Limit maximum fold name length
=> feat: Limit maximum fold name length

qml/FolderGridViewPopup.qml
Modify the font size within an application group
Issue: https://github.com/linuxdeepin/developer-center/issues/8824
=> fix: inconsistent font size

qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml, qml/Main.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/8972
=> fix: folder not support wheel event

qml/FullscreenFrame.qml
=> fix: can not drag and drop item to other page

qml/FolderGridViewPopup.qml
search edit not define..
Issue: https://github.com/linuxdeepin/developer-center/issues/8972
=> fix: folder not support wheel event on window mode

qml/FolderGridViewPopup.qml
Modify the background blur effect of the full-screen application group
Issue: https://github.com/linuxdeepin/developer-center/issues/9374
=> fix: modify the background blur effect

qml/FullscreenFrame.qml
Issues: linuxdeepin/developer-center#8886
=> fix: after dragging the icon to a new page, cannot use tab to select it

qml/windowed/AlphabetCategoryPopup.qml, qml/windowed/AppListView.qml
Modify the display style of ddeCategoryMenu and alphabetCategoryPopup.
Issue: https://github.com/linuxdeepin/developer-center/issues/8807
=> fix: modify the application category hover style

qml/FullscreenFrame.qml, qml/GridViewContainer.qml
在 #287 中已修复，但未集成，复制部分代码到 release/rc2 分支
Issues: linuxdeepin/developer-center#8060
=> fix: can't press return to open the first search result

qml/FolderGridViewPopup.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/9578
Log: 全屏启动器应用组打开时的位置问题
=> fix: 全屏启动器应用组打开时的位置问题

qml/FolderGridViewPopup.qml
Need to distinguish between windowed and full-screen modes
Issue: https://github.com/linuxdeepin/developer-center/issues/9615
=> fix: clicking on an application group in window mode is stuck

qml/Main.qml
Modify the transparency of the window's outer border
Issue: https://github.com/linuxdeepin/developer-center/issues/8342
=> fix: Insufficient transparency of the outer border

CMakeLists.txt, inputeventitem.cpp, inputeventitem.h, qml/FullscreenFrame.qml, qml/windowed/WindowedFrame.qml
Create an InputEventItem object to forward the input events of the input method.
Issue: https://github.com/linuxdeepin/developer-center/issues/8469
=> fix: Can't input Chinese when opening the launcher

qml/windowed/AppList.qml, qml/windowed/FreeSortListView.qml, qml/windowed/WindowedFrame.qml
=> fix: trigger from keyboard also have proper animation

qml/FullscreenFrame.qml, qml/windowed/WindowedFrame.qml
=> feat: fullscreen launcher app-folder animation

qml/FullscreenFrame.qml, qml/windowed/WindowedFrame.qml
应用文件夹背景的假 overlay 的透明度变化动画。
Log:
=> chore: fake overlay opacity animation

translations/dde-launchpad.ts, translations/dde-launchpad_az.ts, translations/dde-launchpad_bo.ts, translations/dde-launchpad_ca.ts, translations/dde-launchpad_es.ts, translations/dde-launchpad_fi.ts, translations/dde-launchpad_fr.ts, translations/dde-launchpad_hu.ts, translations/dde-launchpad_it.ts, translations/dde-launchpad_ja.ts, translations/dde-launchpad_ko.ts, translations/dde-launchpad_nb_NO.ts, translations/dde-launchpad_pl.ts, translations/dde-launchpad_pt_BR.ts, translations/dde-launchpad_ru.ts, translations/dde-launchpad_uk.ts, translations/dde-launchpad_zh_CN.ts, translations/dde-launchpad_zh_HK.ts, translations/dde-launchpad_zh_TW.ts
更新翻译。
Issue: linuxdeepin/developer-center#9898
Log:
=> chore(i18n): update translations

debian/changelog.dch
bump version to 0.8.1
Log: bump version to 0.8.1
=> chore: bump version to 0.8.1

CMakeLists.txt, LICENSES/MIT.txt, debian/control, qml/FullscreenFrame.qml, src/models/CMakeLists.txt, src/models/multipagesortfilterproxymodel.cpp, src/models/multipagesortfilterproxymodel.h, src/models/sortproxymodel.cpp, src/models/sortproxymodel.h
支持全屏启动器图标拖拽释放后的图标移动动画，并为后续移动过程中提供
动画支持进行准备。
Log:
=> feat: fullscreen mode icon move/displace animation

qml/Main.qml
log: KeyboardInteractivity should be OnDemand
=> fix: never get keyboard focus in wayland

qml/FullscreenFrame.qml
=> chore: no longer hide exit fullscreen button on TreeLand

qml/FullscreenFrame.qml
opacity 0.4 -> 0.2
Issue: https://github.com/linuxdeepin/developer-center/issues/10037
=> fix: Insufficient background opacity when opening folder

src/ddeintegration/xml/org.deepin.dde.Appearance1.xml
=> chore: appearance 添加GlobalTheme属性

.reuse/dep5, qml/Helper.qml, qml/IconItemDelegate.qml
too large
Issue: https://github.com/linuxdeepin/developer-center/issues/10027 Log:
=> fix: App names inside folders may grow out of boundry when font size is

debian/changelog
bump to version 0.8.2
Log: bump to version 0.8.2
=> chore: bump to version 0.8.2

debian/changelog
bump version to 0.8.3
Log: bump version to 0.8.3
=> chore: bump version to 0.8.3

qml/Main.qml
Explicitly set the windowRadius to 0
Issue: https://github.com/linuxdeepin/developer-center/issues/9994
=> fix: the full screen window has rounded corners

archlinux/PKGBUILD, qml/FullscreenFrame.qml, src/treelandintegration/CMakeLists.txt
add WaylandClient to find_package
Log:
=> fix: cannot build on archlinux

qml/Main.qml
Adding flags to a fullscreen frame
Issue: https://github.com/linuxdeepin/developer-center/issues/10224
=> fix: fullscreen frame should be a normal window

src/ddeintegration/appearance.cpp
Log: not need wallpaper in treeland
=> fix: crashed when cannot get wallpaper

qml/Main.qml
=> feat: set fullscreen window scope name

qml/Main.qml
Issues: linuxdeepin/developer-center#10200
=> chore: add minimum margin

debian/changelog
bump version to 0.8.4
Log: bump version to 0.8.4
=> chore: bump version to 0.8.4

qml/FolderGridViewPopup.qml
=> fix: just modify windowed mode folder background

qml/FolderGridViewPopup.qml
=> fix: folderGridViewPopup outBorder color is too dark

debian/changelog
bump version to 0.8.5
Log: bump version to 0.8.5
=> fix: bump version to 0.8.5

qml/windowed/AppListView.qml
use ItemDelegate to support dtk hover animation..
=> chore: applistview item delegate tweak

debian/changelog
bump version to 0.8.6
Log: bump version to 0.8.6
=> fix: bump version to 0.8.6

qml/FullscreenFrame.qml, src/models/CMakeLists.txt, src/models/itemarrangementproxymodel.h, src/models/itemspage.cpp, src/models/itemspage.h, src/models/itemspagemodel.cpp, src/models/itemspagemodel.h
Change the swipeview control to listview
Issue: https://github.com/linuxdeepin/developer-center/issues/10365
=> fix: fullscreen frame scrolling bounce effect

debian/changelog
release 0.8.7
Log: bump version to 0.8.7
=> chore: bump version to 0.8.7

debian/changelog
Update translation, prepare branching for release/beige
Log:
=> chore: release dde-launchpad 1.0.0

qml/Helper.qml, qml/windowed/FreeSortListView.qml, qml/windowed/ItemBackground.qml
same color as the hover
Log: update the color
Bug: https://pms.uniontech.com/bug-view-271431.html
=> fix: update the color of a darg-and-drop in FreeSortList

qml/FullscreenFrame.qml
explicitly specify the object of function
Log:
=> fix: undefine "setCurrentIndex" error

debian/changelog
=> chore: bump version to 1.0.2

qml/GridViewContainer.qml, qml/windowed/GridViewContainer.qml
Remove the delayed operation of keyboard keys
Log: missing oblique tab operation
Bug: https://pms.uniontech.com/bug-view-273739.html
=> fix: missing oblique tab operation

qml/Helper.qml, qml/windowed/FreeSortListView.qml
same color as the hover
Log: the color of dropIndicator under the black theme
Bug: https://pms.uniontech.com/bug-view-271431.html
=> fix: the color of dropIndicator under the black theme

qml/FolderGridViewPopup.qml, qml/IconItemDelegate.qml, qml/windowed/AppListView.qml, qml/windowed/BottomBar.qml, qml/windowed/FreeSortListView.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/SideBar.qml
Reduce tooltip delays
Log: tooltip delay time
Bug: https://pms.uniontech.com/bug-view-274485.html
=> fix: tooltip delay time

CMakeLists.txt, qml/FullscreenFrame.qml, qml/windowed/BottomBar.qml, qml/windowed/SideBar.qml, translations/dde-launchpad.ts, translations/dde-launchpad_az.ts, translations/dde-launchpad_bo.ts, translations/dde-launchpad_ca.ts, translations/dde-launchpad_es.ts, translations/dde-launchpad_fi.ts, translations/dde-launchpad_fr.ts, translations/dde-launchpad_hu.ts, translations/dde-launchpad_it.ts, translations/dde-launchpad_ja.ts, translations/dde-launchpad_ko.ts, translations/dde-launchpad_nb_NO.ts, translations/dde-launchpad_pl.ts, translations/dde-launchpad_pt_BR.ts, translations/dde-launchpad_ru.ts, translations/dde-launchpad_uk.ts, translations/dde-launchpad_zh_CN.ts, translations/dde-launchpad_zh_HK.ts, translations/dde-launchpad_zh_TW.ts
Add tips description text and translations
Log: missing tips when button hover
Bug: https://pms.uniontech.com/bug-view-274477.html
=> fix: missing tips when button hover

qml/Main.qml
window radius isn't changed by dcc
Log:
Bug: https://pms.uniontech.com/bug-view-273039.html
=> fix: window radius isn't changed

shell-launcher-applet/package/launcheritem.qml
=> fix: make use of DockPanelPositioner for panel positioning

shell-launcher-applet/package/launcheritem.qml
shell applet 版缺少卸载对话框
cc @RigoLigoRLC
Log:
=> fix: applet version missing uninstall dialog

.reuse/dep5, qml/windowed/AnalysisView.qml, qml/windowed/FrequentlyUsedView.qml, qml/windowed/RecentlyInstalledView.qml, src/models/categorizedsortproxymodel.cpp, src/models/frequentlyusedproxymodel.cpp, src/models/frequentlyusedproxymodel.h
解耦 AppsModel 与其它 model，避免在其它 model 中直接写死 sourceModel 以便后续向 dde-shell 提供的 model 移植。
Log:
=> refactor: decoupling AppsModel and other models

debian/changelog
=> chore: Bump version to 1.0.4

qml/IconItemDelegate.qml, qml/windowed/AnalysisView.qml, qml/windowed/RecentlyInstalledView.qml, src/models/frequentlyusedproxymodel.cpp, src/models/frequentlyusedproxymodel.h, src/models/recentlyinstalledproxymodel.cpp, src/models/recentlyinstalledproxymodel.h
进一步解耦 AppsModel 与其它现有模型，以便后续迁移。
Log:
=> refactor: decoupling AppsModel and other models, Ep. 2

debian/changelog
=> chore: Bump version to 1.0.5

desktopintegration.cpp, desktopintegration.h, qml/windowed/BottomBar.qml
using the shutdown applet first
Log: modify the way of request shutdown
=> fix: modify the way of request shutdown

debian/changelog
=> chore: bump version to 1.99.1

shell-launcher-applet/CMakeLists.txt, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_az.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_bo.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_ca.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_es.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_fi.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_fr.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_hu.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_it.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_ja.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_ko.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_nb_NO.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_pl.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_pt_BR.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_ru.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_uk.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_zh_CN.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_zh_HK.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_zh_TW.ts
修正启动器 applet 分类标题缺失翻译问题
Issue: BUG-287975
Log:
=> fix: category name not translated

debian/changelog
=> chore: Bump version to 1.0.8

qml/FullscreenFrame.qml, qml/Main.qml
avoid undefined appTextColor
Log:
=> fix: add missing property for appTextColor

qml/Helper.qml, qml/IconItemDelegate.qml, qml/windowed/AppListView.qml, qml/windowed/FrequentlyUsedView.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/RecentlyInstalledView.qml
部分区域支持拖拽到任务栏
PMS: BUG-285139
Log:
=> feat: support drag'n'drop to dock for some areas

qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml
pms: BUG-272547
Log: Show autostart icon for autostart apps in the windowed list
=> feat: Show autostart icon for autostart apps in the windowed list

qml/windowed/IconItemDelegate.qml
=> fix: apps on search result not clickable

qml/windowed/WindowedFrame.qml
pms: BUG-295639
Log: Close folder popup in windowed mode
=> fix: Close folder popup in windowed mode

debian/control
=> chore: update section to DDE in debian/control

CMakeLists.txt, launchercontroller.cpp, launchercontroller.h, shell-launcher-applet/package/launcheritem.qml
closeAllPopups when fullscreen launchpad show
log: as title
PMS: BUG-280973
=> fix: quick panel still show while launchpad show

debian/changelog
release 1.99.4
Log: bump version to 1.99.4
=> chore: bump version to 1.99.4

qml/windowed/AppListView.qml, qml/windowed/ItemBackground.qml
Remove repeated FocusBoxBorder.
pms: BUG-297137
=> fix: incorrect FocusBorder for Windowed

qml/windowed/FreeSortListView.qml
自由排序支持拖拽过程中挤动效果。
PMS: BUG-297143
Log:
=> feat: apply drop while dragging for freeform sort view

shell-launcher-applet/package/launcheritem.qml
=> chore: remove warning

debian/changelog
=> chore: bump version to 1.99.6

qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml
修复 AppListView ItemDelegate 的左右 margin 无效的问题,使目前所使用 的组件结构与 FreeSortListView 一致.
PMS: BUG-300939
=> fix: item delegate margin not working in AppListView
