linuxdeepin/dde-launchpad

debian/changelog, main.cpp
发布 0.0.1 技术预览版
1. 所有和拖拽相关的功能暂未实现，会在后续版本中增加  
也因此，暂时无法测试全屏启动器的拖拽后应用分组/抽屉的功能
2. 应用右键菜单中的 “使用代理” 一项无实际效果  
鉴于新 AM 不会支持相关功能，新的对等功能组件还未就绪，此菜单项仅为展示性质的占位作用，也可考虑隐藏处理
3. 卸载功能暂时依赖旧的 dde-application-manager 提供的 d-bus，若旧的 dde-application-manager 被新的替代则对应功能会无作用  
当前计划为提供一个新的组件（尚未集成），并在新的组件中暂时提供和旧 dbus 完全一致的兼容接口
1. 切换到全屏 launcher 后，隐藏 launcher，再从任务栏点击 launcher 图标使其显示，此时 launcher 下方未覆盖 dock 区域，且此时再尝试切换到小 launcher 时会发现小 launcher 也为最大化的尺寸（窗管问题）
2. 小 launcher 无法 tab 切换焦点到左侧的列表项目（dtkdeclarative问题）
3. 全屏 launcher 无法双指侧滑切换到下一屏，但可以侧滑切换到上一屏（qt5 问题）
4. 从全屏 launcher 切换到小 launcher 时，launcher 圆角会消失（可能是窗管或 dtkdeclarative 的问题）
通过 `sudo apt install dde-launchpad` 即可安装新的启动器。在开始测试前，请确保未启动过旧的 launcher 或旧的 launcher 已退出（`killall dde-launcher` 即可）。
测试完毕后，希望回退到旧 launcher 时，手动 `sudo apt install dde-launcher` 即可。
1. …
=> chore: release dde-launchpad 0.0.1 as tech preview

debian/changelog
发布 dde-launchpad 0.0.2
Changelog:
* Use the new application-manager to launch app when possible
* Disable window resizing for window mode launcher https://github.com/linuxdeepin/developer-center/issues/5568
* Support scroll between pages via mouse wheel in fullscreen mode launcher
* Use Qt5's Quick Compiler to pre-compile QML files to C++
Log:
=> chore: release dde-launchpad 0.0.2

CMakeLists.txt, debian/rules, main.cpp
CI scripts or package maintainer can pass `-DVERSION` to CMake to tell the build system which is the `VERSION` that we need to use.
=> chore: read and use VERSION from DEB_VERSION_UPSTREAM

debian/control, src/utils/CMakeLists.txt, src/utils/iconutils.cpp
鉴于 Arch 的 dtkgui 已足够新，此处改用 dtkgui 的接口。
Log:
=> chore: use DIcon::loadNxPixmap from dtkgui

src/utils/iconutils.cpp
使用 DSvgRenderer 与 DIconTheme::findQIcon().
=> chore: use DSvgRenderer and DIconTheme::findQIcon

CMakeLists.txt, debian/changelog
Changelog:
* Hide launcher window right after it lost focus
* Allow using arrow key to change selected app item (https://github.com/linuxdeepin/developer-center/issues/5462)
* Reworked keyboard/Tab-key navigation
* Support ESC key to hide launcher window
* Support using Jianpin to search application (https://github.com/linuxdeepin/developer-center/issues/5461)
=> chore: release dde-launchpad 0.1.0

CMakeLists.txt, src/ddeintegration/CMakeLists.txt, src/gioutils/CMakeLists.txt, src/models/CMakeLists.txt, src/utils/CMakeLists.txt
调整 CMake 写法，试图使其支持 Qt6 与 Dtk6。
注：目前 Dtk6 存在一些问题，所以目前关闭 `PREFER_QT_5` 也无法正常构建出 Qt 6 的 launchpad。
=> feat: support build with Qt 6 and Dtk 6

CMakeLists.txt, debian/changelog
Changelog:
* Initial implementation of the redesigned UI
* Add a new alphabet category screen
* For windowed launcher, always reset searching/focus state when hidding launcher frame
* initial support to build with Qt 6
* remove DRegionMonitor to avoid massive log
Log:
=> chore: release dde-launchpad 0.2.0

CMakeLists.txt, debian/changelog
Changelog:
* Adjust icon hover effect (https://github.com/linuxdeepin/developer-center/issues/6140)
* Ascii item should appears first (https://github.com/linuxdeepin/developer-center/issues/6152)
* Lower-case word should appears first (https://github.com/linuxdeepin/developer-center/issues/6159)
* Reset focus and search state when hide fullscreen frame (https://github.com/linuxdeepin/developer-center/issues/6162)
* Support Enter key to select category in alphabet category view (https://github.com/linuxdeepin/developer-center/issues/6154)
Log:
=> chore: release dde-launchpad 0.2.1

desktopintegration.cpp
=> chore: correct typos in desktopintegration.cpp

CMakeLists.txt, debian/changelog
发布 dde-launchpad 0.3.0
Changelog:
* 全屏启动器支持拖拖拽创建应用文件夹。
* 修复全屏启动器回车启动应用失效的问题 (https://github.com/linuxdeepin/developer-center/issues/6364)
* 移除高亮项切换时的动画 (https://github.com/linuxdeepin/developer-center/issues/6368)
* 隐藏启动器时重置应用文件夹打开状态 (https://github.com/linuxdeepin/developer-center/issues/6369)
* 使用滚轮翻页时重置键盘焦点状态 (https://github.com/linuxdeepin/developer-center/issues/6361)
* 控制中心按钮增加 tooltip (https://github.com/linuxdeepin/developer-center/issues/6365)
Log:
=> chore: release dde-launchpad 0.3.0

debian/control, debian/rules, src/models/multipageproxymodel.cpp
deepin OBS 构建默认构建 Qt 6 版本。
注意：对于现存版本的打包移植，目前仍然建议使用 Qt 5 版本。
测试说明：安装后，先确保之前的 launchpad 实例已退出（`killall dde-launchpad`），然后尝试点击启动器图标使 launchpad 显示出来。若满足下面的简单要求，即说明此 PR 没问题：
1. 可显示出来/切换到小窗口启动器
2. 可显示出来/切换到全屏启动器
3. 小窗口启动器的分类方式切换在点击后可以切换左侧的分类方式
4. 点击应用可以启动应用
5. 点击启动器窗口外侧可使启动器被隐藏
**与 Qt 5 版本 launchpad 相比的显示效果差异**可提 bug，但问题大概都来自 DTK 的 Qt 6 支持。
=> chore(CI): build Qt 6 version by default for deepin CI

qml/WindowedFrame.qml
fix shutdown icon too small on window mode
=> fix: shutdown icon too small on window mode

qml/Main.qml
全屏和小窗口启动器现转而使用不同的两个窗口来管理窗口位置与状态，以此避免共用窗口导致的窗口状态切换时，布局不必要的重新加载导致的卡顿问题。
=> refactor: use two different window for two modes

qml/AppListView.qml, translations/dde-launchpad.ts, translations/dde-launchpad_az.ts, translations/dde-launchpad_bo.ts, translations/dde-launchpad_ca.ts, translations/dde-launchpad_es.ts, translations/dde-launchpad_fi.ts, translations/dde-launchpad_fr.ts, translations/dde-launchpad_hu.ts, translations/dde-launchpad_it.ts, translations/dde-launchpad_ja.ts, translations/dde-launchpad_ko.ts, translations/dde-launchpad_nb_NO.ts, translations/dde-launchpad_pl.ts, translations/dde-launchpad_pt_BR.ts, translations/dde-launchpad_ru.ts, translations/dde-launchpad_uk.ts, translations/dde-launchpad_zh_CN.ts, translations/dde-launchpad_zh_HK.ts, translations/dde-launchpad_zh_TW.ts
Always scroll to the highlight when focus in.
Log: fix highlight not visible when focus in
Issue: https://github.com/linuxdeepin/developer-center/issues/6397
=> fix: highlight not visible when focus in

CMakeLists.txt, debian/changelog
Changelog:
* Rename "Settings" to "Control Center"
* Play sfx when send to desktop
* Support use Enter to launch app in Windowed mode (https://github.com/linuxdeepin/developer-center/issues/6395)
* Support AppStreamQt 1.0
* Change DnD mimetype to text/x-dde-launcher-dnd-desktopId
* Enable cross-page item drag in FullscreenFrame
* Avoid right click launch app in window mode (https://github.com/linuxdeepin/developer-center/issues/6290)
* Support "Pin to top" for favorited items (https://github.com/linuxdeepin/developer-center/issues/6399)
* Fix missing translation in alphabet category view (https://github.com/linuxdeepin/developer-center/issues/6520)
* Use two window for different mode to avoid lagging when switching between modes
* Add dde-application-wizard as dependency
* Clean up …
=> chore: release dde-launchpad 0.4.0

qml/AppListView.qml, qml/FullscreenFrame.qml, qml/GridViewContainer.qml, qml/WindowedFrame.qml
隐藏启动器时，重置可滚动/翻页区域的位置到最顶部/首页。
Issue: https://github.com/linuxdeepin/developer-center/issues/6402
=> fix: reset scrollview/swipeview position when hide

qml/AppListView.qml, qml/WindowedFrame.qml
ButtonPanel has its own focus box, use BoxPanel instead. Optimize margin and radius for highlight item.
Log: fix double focus box
=> fix: double focus box

qml/AppListView.qml, qml/GridViewContainer.qml
* Cause highlight move forcely position highlight item at the top, We revert to ApplyRange.
* Every time focus in, we set the currentIndex to 0, and every time focus out, we clear currentItem.
Log: fix abnormal view of applistview
=> fix: abnormal view of applistview

qml/FullscreenFrame.qml
keep searchEdit focus when flip page
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/6398
=> fix: reset keyboard focus even searchEdit focus

CMakeLists.txt, debian/changelog
Please refer to debian/changelog for detailed changelog
Log:
=> chore: release dde-launchpad 0.4.1

qml/Main.qml
it's maybe to avoid bugs in dark theme.
Issue: https://github.com/linuxdeepin/developer-center/issues/6842
=> fix: full screen always dark theme

desktopintegration.cpp, desktopintegration.h, qml/Main.qml, src/ddeintegration/ddedock.cpp, src/ddeintegration/ddedock.h, src/ddeintegration/xml/org.deepin.dde.daemon.Dock1.xml
In first presentation, there is no distance to dock. But the second presentation will bring a spacing to Dock. Always add a spacing to Dock.
Log: fix position jitter between two presentations
Issue: https://github.com/linuxdeepin/developer-center/issues/6733
Depends: https://github.com/linuxdeepin/dde-dock/pull/956
=> fix: position jitter between two presentations

src/utils/iconutils.cpp
It's maybe a bug for deepin-app-store-tool. App's icon is installed
in /opt, the tool will create a link for it's icons, but the action
is async, icon-theme.cache is not ready when launchpad is read.
and we only ensure display an X icon when icon is invalid.
Issue: https://github.com/linuxdeepin/developer-center/issues/6860
=> fix: failed to fallback default icon

src/models/appsmodel.cpp, src/utils/CMakeLists.txt, src/utils/iconutils.cpp, src/utils/iconutils.h
It maybe a bug for qt.
xdgicon has not adapt to qt6, so we use Qt's QIconLoaderEngine
to find icon for xdg icon in dtkgui, but `icon-theme.cache` is read once in
QIconCacheGtkReader, so it's not updated even if `gtk-update-cache-icon`
is executed in deepin-app-store-tool before reading icon.
we release cache when `changed` signal received.
Issue: https://github.com/linuxdeepin/developer-center/issues/6860
=> fix: can't find icon in qt6

launchercontroller.cpp, launchercontroller.h, qml/Main.qml
复用了现有的 timer 来避免在无混成时切换 launchpad 模式时失去焦点导致的窗口隐藏。
Issue: https://github.com/linuxdeepin/developer-center/issues/6818
=> fix: use timer to avoid window hide caused by switching mode

CMakeLists.txt, debian/changelog
Changelog:
* Fix window mode position jitter (linuxdeepin/developer-center#6733)
* Fix icon missing (linuxdeepin/developer-center#6860)
* Provide a built-in compulsory-for-DDE app list (linuxdeepin/developer-center#6883)
* Enable clipping for app folder page view
* Fix scroll failed in some case (linuxdeepin/developer-center#6897)
* Avoid window mode hide caused by activeChanged (linuxdeepin/developer-center#6818)
Log:
=> chore: release dde-launchpad 0.4.3

desktopintegration.cpp, desktopintegration.h, launchercontroller.cpp, qml/FullscreenFrame.qml, qml/Main.qml
临时为 TreeLand 提供的修改。此提交后续应当回退。修改内容如下：
1. TreeLand 下默认全屏
2. 隐藏切换到窗口模式的按钮
=> chore: quick dirty fix for TreeLand

qml/Main.qml
Use layout instead of explicit width and height.
Log: fix layout error in uninstall dialog
Depends: https://github.com/linuxdeepin/dtkdeclarative/pull/278
=> fix: layout error in uninstall dialog

qml/FullscreenFrame.qml
Use implicit width to tell column layout the preferred width. Adjust preferred width to 280.
Log: fix search edit width not correct
=> fix: search edit width not correct

CMakeLists.txt, debian/changelog
Changelog:
* Ensure icon change when theme change
* Show scrollbar for window mode app gridview (linuxdeepin/developer-center#6202)
* Ensure numkey to trigger quick search (linuxdeepin/developer-center#6373)
* Add horizontal spacing for windowed mode grid view (linuxdeepin/developer-center#6372)
* Ensure return to main view when press key on alphabet view (linuxdeepin/developer-center#6156)
* Add window blur for windowed mode (linuxdeepin/developer-center#7125)
* Adapt UI changes according to designer
Log:
=> chore: release dde-launchpad 0.4.5

CMakeLists.txt, debian/changelog, src/models/favoritedproxymodel.cpp
Changelog:
* Adapt UI changes according to designer
* Fix tab and space and trigger quick search
* Add pre-defined apps to launchpad favorited apps
Log:
=> chore: release dde-launchpad 0.4.6

desktopintegration.cpp, src/ddeintegration/appmgr.cpp, src/ddeintegration/appmgr.h
Use dde-application-manager's dbus API to manage desktop shortcut and autostart.
cc @ComixHe
=> chore: use AM api to manage shortcut and autostart

qml/FullscreenFrame.qml, qml/IconItemDelegate.qml, qml/WindowedFrame.qml
=> chore: use DciIcon from dtkdeclarative

qml/WindowedFrame.qml
Tab 不应当触发快速搜索
Issues: linuxdeepin/developer-center#7204
=> fix: should skip tab for fast search

src/ddeintegration/appmgr.cpp, src/ddeintegration/appmgr.h
We can reuse AppItem's handler as interface.
fallback to Name if GenericName is empty for X_Deepin_Vendor.
=> fix: memory leak when launching app by AM

CMakeLists.txt, main.cpp, qml.qrc, qml/Main.qml, qml/windowed/AlphabetCategoryPopup.qml, qml/windowed/CMakeLists.txt, qml/windowed/IconItemDelegate.qml, qml/windowed/WindowedFrame.qml
In order to facilitate the next step of porting to dde-shell.
Windowed's IconItemDelegate is different with FullWindow, so
we add an new IconItemDelegate.
=> refact: separate Windowed as a plugin

qml/windowed/RecentlyInstalledView.qml, src/models/recentlyinstalledproxymodel.cpp, src/models/recentlyinstalledproxymodel.h
RecentlyInstalledProxyModel is an singleton model, so it will
not execute componentComplete for QQmlParserStatus.
We add a property to remove sourceModel's binding.
=> fix: recentlyInstalledModel is empty

qml/FullscreenFrame.qml
支持使用键盘焦点与鼠标滚轮来在全屏首尾页切换。
注：算是绕过的方法。通过拖拽仍然不能在首尾衔接切换，而通过滚轮或键盘
焦点切换时的效果也类似直接点击首尾页码的跳转。
Log:
=> feat: allow wrap between first and last page

qml/GridViewContainer.qml, qml/IconItemDelegate.qml, qml/windowed/IconItemDelegate.qml, qml/windowed/SearchResultView.qml, qml/windowed/SideBar.qml
fix: The icons for mode switching on the left side are hard to see when the wallpaper is dark
DciIcon does not automatically handle color palettes and themes
Add processing code
Issue: https://github.com/linuxdeepin/developer-center/issues/7571
=> fix: The icons for mode switching on the left side are hard to see when the wallpaper is dark

qml/FullscreenFrame.qml, qml/windowed/WindowedFrame.qml
在奇怪的情况下，使用 Ctrl+Space 会输入 `\0` （即NULL）字符，这时不应当将其输入到搜索框内。
Issue: https://github.com/linuxdeepin/developer-center/issues/7630 Log:
=> fix: avoid input \0 to SearchEdit

qml/FullscreenFrame.qml
小窗口界面的原对应文案已经移到了 SearchResultView，全屏位置同步更新文案位置。
Issue: https://github.com/linuxdeepin/developer-center/issues/7631
=> fix: reuse translation from SearchResultView

qml/FullscreenFrame.qml, qml/windowed/WindowedFrame.qml
当无键盘焦点（实际是键盘焦点位于根节点组件）时，支持使用回车/方向键切换焦点到应用区域。
Issue: https://github.com/linuxdeepin/developer-center/issues/7244
=> feat: focus on app item when we do not have focus

qml/windowed/AppList.qml
fix not close the menu when scrolling the app listview
Log: close the menu when scrolling mouse
Influence: close the menu when scrolling mouse
Issus: https://github.com/linuxdeepin/developer-center/issues/7646
=> fix: close menu when scrolling the app listview

src/ddeintegration/appmgr.cpp, src/ddeintegration/appmgr.h
Launching app by `dde-am` tools instead of calling dbus directly.
Updating launchedTimes from DConfig.
=> refact: updating launchedTimes from DConfig

main.cpp, qml/Main.qml
it depends libdtk6declarative's runtime.
reset dconfig's cache value by override file.
=> refact: only specify fullscreen as dark theme

src/models/frequentlyusedproxymodel.cpp
We only compare launched app by us. and it's LaunchedTimes is
not zero.
=> fix: filter other launched app in frecently-used

CMakeLists.txt, debian/changelog
* Adapt post-beta-3 UI changes according to designer
* Drop Qt 5 and DTK 5 build support
* Switch to use AM API to manage apps, shortcut and autostart
* Quick-search-related shortcuts and key navigation tweaks
* Hide the 'use proxy' placeholder menu entry
* Remove invalid empty pages when app uninstalled
* Remove bookmark section, add recently installed section to UI
* Add search rule to match untranslated desktop 'Name'
* Add recently installed apps section to UI
* Add 'free sort' mode to windowed mode app list
* Introduce new debug option for developer
* Add window title for kwin to match correct window on x11
* Wrap between first and last page when using key navigation
* Add an unit test for 'ItemPage'
* Update translation from Hosted Weblate
Log:
=> chore: release dde-launchpad 0.5.0

qml/FullscreenFrame.qml, src/models/itemarrangementproxymodel.cpp, src/models/itemarrangementproxymodel.h, src/models/itemspage.cpp, src/models/itemspage.h
drag the item from the last page to the right to create a new page
Log: fix drag item cannot create a new page
Issues: https://github.com/linuxdeepin/developer-center/issues/7633
Influence: drag item can create a new page
=> fix: drag item cannot create a new page

src/models/itemspage.cpp, tests/itemspagetest.cpp
Dragging the last item on the last page will not delete the empty page
Log: moving the last one item not remove empty page
Influence: auto remove empty page
=> fix: moving the last one item not remove empty page

.obs/workflows.yml
debian sid 的 Qt 版本过低，以及一些别的问题，导致 debian 构建现阶段无法通过。故目前移除处理。
Log:
=> chore(CI): remove debian sid obs build

qml/Main.qml
全屏失去焦点时也隐藏启动器。
Issue: https://github.com/linuxdeepin/developer-center/issues/7635
=> chore: also hide fullscreen frame when lost focus

launchercontroller.cpp, launchercontroller.h, qml/windowed/AppListView.qml, qml/windowed/FrequentlyUsedView.qml, qml/windowed/RecentlyInstalledView.qml, qml/windowed/SearchResultView.qml, qml/windowed/WindowedFrame.qml
Log: Set word weight to 500, size to T7, color to 60% transparency
Issue: https://github.com/linuxdeepin/developer-center/issues/7786
=> fix: The category title is too black

desktopintegration.cpp, qml/Main.qml, src/ddeintegration/ddedock.cpp, src/ddeintegration/ddedock.h
dock doesn't have space margin, so just use 10px.
Issue: https://github.com/linuxdeepin/developer-center/issues/7781
=> fix: mini mode window margin not set

qml/FullscreenFrame.qml, qml/GridViewContainer.qml, qml/windowed/GridViewContainer.qml, qml/windowed/SearchResultView.qml, qml/windowed/WindowedFrame.qml
行为调整，当正在搜索时，回车将直接启动结果中被选中的结果（即第一个结果），而不再是将焦点移到搜索区域。注意，当前实现仍与4/9讨论的预期行为不同，预期是希望搜索过程中也始终显示选中项，即搜索结果区域无焦点时，选中项也有一个近似于hover效果的指示效果的。
未在搜索时的行为不变（即，如果焦点在搜索框但没输入任何关键词就按下回车，此时会将焦点切换到应用区域）。
=> feat: press enter to open the 1st result

src/models/itemspage.cpp
dragging an item into folder, toPageIndex is -1, need to recalculate.
Log: fix dragging an item into folder causes crash
Influence: dragging item into folder
=> fix: fix dragging an item into folder causes crash

qml/windowed/BottomBar.qml
Adding an control as SearchEdit's parent.
=> fix: incorrect hover area for SearchEdit

qml/Main.qml
I don't know why it exists when org.deepin.ds.dock is loaded with
the org.deepin.ds.launchpad.
Using layershell to anchor the window's position.
issue: https://github.com/linuxdeepin/developer-center/issues/7824
=> fix: uninstallDialog doesn't center in screen

CMakeLists.txt, debian/changelog
Changelog:
* Adapt to dde-shell (linuxdeepin/developer-center#5810)
* Support drag item to create new page (linuxdeepin/developer-center#7633)
* Remove empty page caused by item rearrangement
* Fix list position while switching tab focus (linuxdeepin/developer-center#7684)
* Set default tab focus to the app area
* Add fallback icon for apps that have no icon (linuxdeepin/developer-center#5608) (linuxdeepin/developer-center#7742)
* Hide fullscreen launchpad when lost focus (linuxdeepin/developer-center#7635)
* UI tweaks (linuxdeepin/developer-center#7774) (linuxdeepin/developer-center#7775) (linuxdeepin/developer-center#7778) (linuxdeepin/developer-center#7779) (linuxdeepin/developer-center#7782) (linuxdeepin/developer-center#7786) (linuxdeepin/developer-center#7781) …
=> chore: release dde-launchpad 0.6.0

qml/Helper.qml, qml/Main.qml, qml/windowed/GridViewContainer.qml, qml/windowed/IconItemDelegate.qml
IconItemDelegate's height is not the same as cellWidth
Issue: https://github.com/linuxdeepin/developer-center/issues/7624
=> fix: focus rect not correct

qml/FolderGridViewPopup.qml
应用文件夹的显示名称需要 clip 以免被显示到外面。
Issue: linuxdeepin/developer-center#7949
Log:
=> fix: should clip app folder name text

CMakeLists.txt
由于 CMP0071，CMake 的 AUTOMOC 跳过了一些生成的 CPP 文件的处理，例如
launcher-qml-windowed_org_deepin_launchpad_windowedPlugin.cpp。我们 直接提高 CMake 最小版本来处理此问题。
Log:
=> fix: FTBFS on Archlinux caused by CMake CMP0071

CMakeLists.txt, debian/changelog
Changelog:
* Remember app list sort type (linuxdeepin/developer-center#7652)
* Fix icon overlap on HiDPI (linuxdeepin/developer-center#7634)
* Fix focus rect (linuxdeepin/developer-center#7624)
* Disable "Send to Dock" menu for app group
* Clip folder name text (linuxdeepin/developer-center#7949)
* Disable invisible menu items to avoid tab focus
* Fix FTBFS caused by CMP0071 CMake policy
* Update style when edit folder title (linuxdeepin/developer-center#7953)
* Fix category mode section title spacing (linuxdeepin/developer-center#7938)
* Full Screen Grid is now 4x8 (linuxdeepin/developer-center#7987)
* Various UI fixes
Log:
=> chore: release dde-launchpad 0.6.1

main.cpp
虽然这个修复实际对 dde-shell 版的 launchpad 不起作用，但还是修正一下。
Log:
=> chore: incorrect log file location

qml/windowed/AppListView.qml
设计核对，将分类列表的 section header 与 item 的间距高度从 8 调整至
6。
Issue: linuxdeepin/developer-center#7938
Log:
=> chore(UI): section header spacing from 8 to 6

main.cpp, qml/IconItemDelegate.qml
Don't use inactive palette group and don't change width and height when switching from windowed to fullscreen.
Log: fix useless refresh for app icons
Issue: https://github.com/linuxdeepin/developer-center/issues/7826
Depends: https://github.com/linuxdeepin/dtkdeclarative/pull/319
=> fix: useless refresh for app icons

debian/changelog
Changelog:
* Drag operation now requires 300ms press-n-hold (linuxdeepin/developer-center#6359)
* Don't show hover background when dragging (linuxdeepin/developer-center#7944)
* Adjust item name color (linuxdeepin/developer-center#7940)
* Fix splitter line styling (linuxdeepin/developer-center#7930)
* Adjust fullscreen grid item count (linuxdeepin/developer-center#7938)
* Adjust item background color (linuxdeepin/developer-center#7935)
* Various UI fixes
Log:
=> chore: release dde-launchpad 0.6.2

CMakeLists.txt, debian/changelog
Changelog:
* Avoid necessary icon reload (linuxdeepin/developer-center#7826)
* Add missing background for two buttons (linuxdeepin/developer-center#7935)
* Fix bind loop warnings
* Fix glitch icons when icon name is blank/empty
* Category type default to freeform sort type (linuxdeepin/developer-center#8022)
* Various UI fixes
Log:
=> chore: release dde-launchpad 0.6.3

docs/DConfig.md, src/models/org.deepin.dde.launchpad.appsmodel.json
json 配置中添加 compulsoryAppIdList 以便后续覆盖默认行为，更新 DConfig 文档。
Log:
=> chore: add compulsoryAppIdList, update DConfig doc

dde-shell-wrapper/package/main.qml, debian/control
存在打断dde-shell调整dock高度动作的问题
Issue: https://github.com/linuxdeepin/developer-center/issues/7943
Log: 为dde-shell提供隐藏自身的插件接口
=> feat: 为dde-shell提供隐藏自身的插件接口

CMakeLists.txt, debian/changelog
Changelog:
* Fix incorrect window mode launcher window position (linuxdeepin/developer-center#8072)
* Update DConfig documentation
* Only use normal state for DciIcon (linuxdeepin/developer-center#8050)
* Add API to allow dde-shell hide launcher window (linuxdeepin/developer-center#7943)
Log:
=> chore: release dde-launchpad 0.6.4

qml/FullscreenFrame.qml, qml/windowed/FreeSortListView.qml, src/models/itemarrangementproxymodel.cpp
避免因接受任意的拖拽行为而导致崩溃，包括：
1. 松开（drop）时检查 MIME 是否与预期匹配，不匹配则直接返回
2. 尝试应用位置调整行为时，检查原始拖放的项目是否真实存在
Log:
=> fix: check MIME before accepting drop

qml/FullscreenFrame.qml
全屏启动器 dock 预留的空白区域需要考虑高分屏缩放情况。dock 对应 dbus 提供的数值是缩放后的数值，所以需要除掉。
=> fix: reserved padding for dock should be HiDPI aware

qml/FullscreenFrame.qml, src/models/itemarrangementproxymodel.cpp
允许拖拽到空白区域。
根据追溯，之前屏蔽当前页面drop item的原因是避免鼠标拖拽到屏幕两侧并
在未触发翻页的情况下即释放鼠标（此时应当什么也不做，使应用归位）。
此逻辑致使无法将item拖拽到当前页面最后的空白位置，也误伤了非同一文件
夹但在同一页面的情况。
Issue: linuxdeepin/developer-center#7640
Log:
=> fix: should allow drop on empty space

CMakeLists.txt, debian/changelog
Changelog:
* Check MIME before accepting drop and avoid related crash
* Various UI fixes (linuxdeepin/developer-center#8182)
* Ensure text elide when necessary (linuxdeepin/developer-center#8183)
* Allow same-folder drop (linuxdeepin/developer-center#7640)
Log:
=> chore: release dde-launchpad 0.6.7

qml/FullscreenFrame.qml, qml/IconItemDelegate.qml
* Revert the previous fix.
* Fix with a different policy.
=> fix: swipe and drag conflicts

qml/IconItemDelegate.qml
字太大，显示不下两行的情况下，显示一行，并增加 tooltip。
Issue: linuxdeepin/developer-center#8239
Log:
=> fix: show single line when font is too large to show two lines

CMakeLists.txt, debian/changelog
Changelog:
* Fix keyboard focus navigation (linuxdeepin/developer-center#8135)
* Fix search icon color in fullscreen (linuxdeepin/developer-center#8182)
* Fix swipe and drag conflict, take two.
* Disable page wrap in fullscreen
* Fix text overflow when font size is too large (linuxdeepin/developer-center#8239)
* Various UI fixes
Log:
=> chore: release dde-launchpad 0.6.8

qml/windowed/BottomBar.qml
Use a smaller padding for search edit because when use the largest font, the text might be clipped.
Log: fix padding error in large font
Issue: https://github.com/linuxdeepin/developer-center/issues/8295
=> fix: padding error in large font

src/models/itemarrangementproxymodel.cpp
When uninstalling an application, the check for empty application groups is not handled.
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8367
=> fix: There are empty application groups.

qml/FolderGridViewPopup.qml, qml/IconItemDelegate.qml
Adjust the rounded corners of the small window folder and the item background color
Issue: https://github.com/linuxdeepin/developer-center/issues/8338
=> fix: The size of the rounded corners in the small window folder is incorrect

qml/Main.qml
Limitting windowed window's size.
Issue: https://github.com/linuxdeepin/developer-center/issues/7647
=> fix: still can resize when effects closed

src/models/itemarrangementproxymodel.cpp, src/models/itemspage.cpp, src/models/itemspage.h
When there is only one application in the group and it is dragged and dropped within the same group, the drag and drop process is not handled.
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/8384
=> fix: Launchpad crashes.

qml/IconItemDelegate.qml
the tap gesture is not canceled default, it will trigger menu repeated.
Issue: https://github.com/linuxdeepin/developer-center/issues/8368
=> fix: two popup when right folder's popup item

qml/IconItemDelegate.qml, qml/windowed/FreeSortListView.qml, src/models/appitem.cpp, src/models/itemarrangementproxymodel.cpp, src/models/itemarrangementproxymodel.h
Show default icon when icon is empty, and add a field to distinguish between folders and appitems
Issue: https://github.com/linuxdeepin/developer-center/issues/8396
=> fix: appItem without icon field clicking to start causing crash

debian/changelog
Update changelog for 0.6.9 release
=> chore: bump version to 0.6.9

qml/FolderGridViewPopup.qml
When it is too long, display a thumbnail and give a ToolTip prompt
Issue: https://github.com/linuxdeepin/developer-center/issues/8336
=> fix: Not displaying thumbnail when folder name is too long

qml/GridViewContainer.qml, qml/windowed/GridViewContainer.qml
it maybe a bug for dtk, and we also don't need use clip.
Issue: https://github.com/linuxdeepin/developer-center/issues/8468
=> fix: missing blur when clipped

CMakeLists.txt, debian/changelog
Changelog:
* Fix missing blur (linuxdeepin/developer-center#8468)
* Workaround QTBUG-125139 (linuxdeepin/developer-center#8475)
* Fix blank page after drag (linuxdeepin/developer-center#8358) (linuxdeepin/developer-center#8363)
* Check Ctrl key before accepting quick search (linuxdeepin/developer-center#8463)
* Avoid hang when drop to last item in page (linuxdeepin/developer-center#8457)
* Avoid two apps launched when click in folder (linuxdeepin/developer-center#8462)
* Ensure scrollbar visible for search result (linuxdeepin/developer-center#7833)
* Fix thumbnail not shown when folder name too long (linuxdeepin/developer-center#8336)
* Allow continue search when search edit is not focused (linuxdeepin/developer-center#7627)
* Fix enter to launch current app …
=> chore: release dde-launchpad 0.6.10

qml/AppItemMenu.qml
Likely a DTK issue but anyway...
Issue: linuxdeepin/developer-center#8477
=> fix: ensure AppItemMenu is modal

qml/FullscreenFrame.qml, qml/windowed/WindowedFrame.qml
We should at least also check keypad modifier as well
Related: linuxdeepin/dde-launchpad#269
Issue: linuxdeepin/developer-center#8495
=> fix: numpad quick search not working

qml/AppItemMenu.qml, qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml, qml/Main.qml, qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml, qml/windowed/FrequentlyUsedView.qml, qml/windowed/RecentlyInstalledView.qml, qml/windowed/SearchResultView.qml
目前的 showContextMenu() 最后三个参数一方面只看参数值完全不知道是干嘛的，另一方面原本涉及到的需求暂时被裁切了。于是此处对此函数的参数进行调整，移除了后三个参数并给定了合适的默认行为，并另外提供了一个参数用来为构造的菜单可选的指定一些可能所需的额外属性。
与 linuxdeepin/developer-center#8472 稍有关系（但此提交不解决对应的 问题）
Log:
=> chore: rework how showContextMenu() works

qml/FolderGridViewPopup.qml, qml/GridViewContainer.qml, qml/windowed/GridViewContainer.qml
add clip, and only doesn't clip it in FolderGridViewPopup.
=> fix:  search result overflow

CMakeLists.txt, debian/changelog
Changelog:
* Fix search result overflow
* Ensure AppItemMenu is modal (linuxdeepin/developer-center#8477)
* Fix numpad quick search not working (linuxdeepin/developer-center#8495)
Log:
=> chore: release dde-launchpad 0.6.11

desktopintegration.cpp, src/models/org.deepin.dde.launchpad.appsmodel.json
dde-control-center's desktop has changed in commit
https://github.com/linuxdeepin/dde-control-center/pull/1624
=> fix: dde-control-center can be uninstalled

debian/changelog, qml/AppItemMenu.qml, qml/FolderGridViewPopup.qml, qml/Main.qml
We use window instead of Item as Menu's parent.
TODO: it's a bug for dtk.
Issue: https://github.com/linuxdeepin/developer-center/issues/8468
=> fix: missing blur for Menu when it's parent is clip

qml/FolderGridViewPopup.qml
as title.
Issue: https://github.com/linuxdeepin/developer-center/issues/8409
=> fix: missing border for FlolderPopup in windowed

CMakeLists.txt, debian/control, desktopintegration.cpp, src/ddeintegration/CMakeLists.txt
之前由于仓库尚不存在 1.x 版本的 AppStream 软件包，所以尽管 debian 依赖写了对 appstreamqt 的依赖，但实际对应的支持是不会被启用的。现 AppStream 1.0.3 已进入 deepin 仓库，故开始强制要求 AppStream 依赖 存在。
与 linuxdeepin/dde-launchpad#281 有一定相关性（原为 AppStream 配置 不存在时提供的后备方案）。
=> chore: now require AppStreamQt 1.0

qml/FolderGridViewPopup.qml
Modify the rounded corners of windowed to 20
Issue: https://github.com/linuxdeepin/developer-center/issues/8336
=> feat: modify application group rounded corners

src/models/org.deepin.dde.launchpad.appsmodel.json
避免 fcitx 与打印机组件从 launcher 中被卸载。
请注意：此列表以当前需求最新版为准，原始 issue 中列出的强制依赖项目
与最新需求并不完全相符，例如计算器与 UOS AI 在最新需求中均为非强制
依赖。
另请注意：应当尽可能避免 launchpad 硬编码不可卸载的应用列表。若应用
本身被视为桌面环境的强制依赖（卸载会导致桌面环境不可用），则应用应当
使用 AppStream 元信息标注自己为不可被卸载。launchpad 会遵循此信息。
可参见控制中心与应用商店当前的做法。
Issue: linuxdeepin/developer-center#8674
Log:
=> fix: should avoid fcitx and printer get uninstalled

qml/AppItemMenu.qml, qml/Main.qml, qml/windowed/FreeSortListView.qml, src/models/itemarrangementproxymodel.cpp, src/models/itemarrangementproxymodel.h
添加菜单项，允许移动 item 到最前（仅针对顶层 item 或应用文件夹有效）
此提交也允许对文件夹进行右键点击以供使用对应的菜单项（但当前只有这个
新增项可点击）。另外，本身就处于第一项的 item 不会显示移至顶部菜单。
新增菜单项暂未翻译，文案为暂定文案。
Log:
=> feat: add option to move item to top in FreeSortListView

qml/windowed/AppListView.qml
作用域小了，往外移一个级别即可
Issue: https://github.com/linuxdeepin/developer-center/issues/8584
=> fix: AppListview can not launchApp onKeypressed

qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml
1. 小启动器应用组指示器改为5x5 间距5，大启动器的主页和应用组改为10x10间距10
2. 颜色统一
Issue: https://github.com/linuxdeepin/developer-center/issues/8688
=> fix: PageIndicator style issue

src/ddeintegration/appmgr.cpp
According to Dtk::Core::DDesktopEntry::ddeDisplayName, GenericName should only be used when X-Deepin-Vendor equals to "deepin"
Some desktop entry files X-Deepin-Vendor is set to "user-custom", should use Name as displayName (e.g. deepin-IDE)
Log: In parseDBus2AppItem, use GenericName as displayName only when X-Deepin-Vendor equals to "deepin"
=> fix: AppItem displayName is incorrect for desktop files which X-Deepin-Vendor is not "deepin"

src/quick/launcherfoldericonprovider.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/8803
=> fix: folder icon radius too small

CMakeLists.txt, debian/changelog
Changelog:
* Fix missing border in popup (linuxdeepin/developer-center#8409)
* Now requires AppStreamQt 1.0
* App group round corner (linuxdeepin/developer-center#8336)
* Update built-in compulsory app list (linuxdeepin/developer-center#8674)
* Show highlighted item all the time in fullscreen mode
* Add menu entry to bring item to front in freeform sort mode
* Update translations
* Fix Enter and Space key not able to launch app (linuxdeepin/developer-center#8584)
* PageIndicator styling fix (linuxdeepin/developer-center#8688)
* Fix menu popup focus (linuxdeepin/developer-center#7629)
* Fix incorrect X-Deepin-Vendor check
Log:
=> chore: release dde-launchpad 0.7.0

src/models/appsmodel.cpp, src/models/appsmodel.h
/opt/apps installed will update hicolor
watch /usr/share/icons/hicolor/icon-theme.cache modified to update icon cache..
Issue: https://github.com/linuxdeepin/developer-center/issues/8577
=> chore: try to update icon cache again

qml/AppItemMenu.qml
this commit revert 9a4c4e2
Issue: https://github.com/linuxdeepin/developer-center/issues/8862
或许 https://github.com/linuxdeepin/developer-center/issues/8571 需要重新测试一下？ @BLumia @18202781743
=> Revert: " fix: more than one hover status for Menu"

qml/IconItemDelegate.qml
Issues: linuxdeepin/developer-center#8689
=> fix: folder icons did not update with the theme

qml/windowed/AppListView.qml, qml/windowed/FreeSortListView.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/8244
Log: Show full app name tooltips for truncated app name in windowed mode
=> fix: Show full app name tooltips for truncated app name in windowed mode

src/models/itemarrangementproxymodel.cpp, src/models/itemspage.cpp, src/models/itemspage.h
- 拖拽唯一的图标到当前页不处理
- 拖拽到唯一的图标到自动新增的页先保留空页在插入最后清理
pages 如果提前清理了，然后去访问新的页码会超出范围
Issue: https://github.com/linuxdeepin/developer-center/issues/8384
=> fix: crash on dnd the only item in the page

src/models/itemarrangementproxymodel.cpp
itemount instead of pagecount
Issue: https://github.com/linuxdeepin/developer-center/issues/8947
=> fix: folder did not remove without item

qml/windowed/BottomBar.qml, qml/windowed/WindowedFrame.qml
当前外边距与设计不符
Issues: linuxdeepin/developer-center#8694
=> fix: modify the margins

qml/windowed/SideBar.qml
Use sourceSize to control the size of DciIcon
Issue: https://github.com/linuxdeepin/developer-center/issues/8805
=> fix: View switch button position drift in window mode

qml/FullscreenFrame.qml, qml/windowed/BottomBar.qml
Issues: linuxdeepin/developer-center#8980
=> chore: clear search text when switching mode

qml/FullscreenFrame.qml, qml/windowed/BottomBar.qml, qml/windowed/WindowedFrame.qml
使用 Keys.forwardTo 代替判断 event.text
Issues: linuxdeepin/developer-center#8495
=> fix: the numeric keypad cannot input

src/ddeintegration/appearance.cpp, src/ddeintegration/appearance.h, src/ddeintegration/xml/org.deepin.dde.Appearance1.xml
fullscreen show to update background image
先获取所有工作区的壁纸一次性全给（模糊）缓存了，然后获取当前工作区的壁纸直接设置。
后面全屏再显示时直接从缓存里面取缓存好的（模糊）壁纸，这样比较快。
Issue: https://github.com/linuxdeepin/developer-center/issues/8828
=> fix: udpate blur background on visible changed

qml/FolderGridViewPopup.qml
Issue: https://github.com/linuxdeepin/developer-center/issues/8802
=> fix: folder popup selectionColor not highlight

src/models/appitem.cpp, src/models/appsmodel.cpp
- reset model to fix black square icon
- if icon is fullpath convert to url
Issue: https://github.com/linuxdeepin/developer-center/issues/8577
=> fix: little black square icon show again

src/models/org.deepin.dde.launchpad.appsmodel.json
Modify the dde-printer's desktop file name to dde-printer.desktop
Issue: https://github.com/linuxdeepin/developer-center/issues/8674
=> fix: dde-printer can be uninstalled

qml/FullscreenFrame.qml
Page indicator not shown when searching
Issue: https://github.com/linuxdeepin/developer-center/issues/8655
=> fix: PageIndicator not shown when searching

qml/FolderGridViewPopup.qml
maybe TapHander's bug
- https://github.com/linuxdeepin/developer-center/issues/9009
- https://github.com/linuxdeepin/developer-center/issues/8832
=> fix: item after folder can be operated

qml/Main.qml
adjust Inner border and outer border
Issue: https://github.com/linuxdeepin/developer-center/issues/8342
=> fix: border color issue

debian/changelog, qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml, qml/Main.qml, qml/windowed/BottomBar.qml, qml/windowed/SideBar.qml, qml/windowed/WindowedFrame.qml, src/ddeintegration/appearance.cpp, src/ddeintegration/appearance.h, src/ddeintegration/xml/org.deepin.dde.Appearance1.xml, src/models/appitem.cpp, src/models/appsmodel.cpp, src/models/org.deepin.dde.launchpad.appsmodel.json, translations/dde-launchpad_pl.ts
*  linuxdeepin/developer-center#8694
*  linuxdeepin/developer-center#8805
*  linuxdeepin/developer-center#8980
*  linuxdeepin/developer-center#8495
*  linuxdeepin/developer-center#8828
*  linuxdeepin/developer-center#7949
*  linuxdeepin/developer-center#8577
*  linuxdeepin/developer-center#8824
*  linuxdeepin/developer-center#8674
*  linuxdeepin/developer-center#8655
*  linuxdeepin/developer-center#9009
*  linuxdeepin/developer-center#8832
*  linuxdeepin/developer-center#8972
*  linuxdeepin/developer-center#8342
=> Release 0.7.3

launchercontroller.cpp, launchercontroller.h, src/ddeintegration/appearance.cpp
window frame to fullscreen frame update current background
Issue: https://github.com/linuxdeepin/developer-center/issues/8828
=> fix: udpate blur background on window mode changed

qml/windowed/AppListView.qml
Modify the color of the menuitem hover to be the same as AlphabetCategoryPopup
Issue: https://github.com/linuxdeepin/developer-center/issues/8807
=> fix: modify the color property of the menuitem hover

src/models/appsmodel.cpp
Qt‘s icon cache still needs to update
=> fix: utools icon not found

debian/changelog, launchercontroller.cpp, launchercontroller.h, qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml, src/ddeintegration/appearance.cpp
- https://github.com/linuxdeepin/developer-center/issues/8886
- https://github.com/linuxdeepin/developer-center/issues/8972
- https://github.com/linuxdeepin/developer-center/issues/8828
=> bump version to 0.7.4

launchercontroller.cpp, launchercontroller.h, qml/Main.qml
为了解决 https://github.com/linuxdeepin/developer-center/issues/6818， 设置了忽略切换模式后 1s 内的 activeChanged 事件。
导致切换到窗口模式后， 1s 内点击空白处，窗口无法再关闭
Issues: linuxdeepin/developer-center#8916
=> fix: cannot hide the window after switching to windowed mode

debian/changelog, launchercontroller.cpp, launchercontroller.h, qml/FolderGridViewPopup.qml, qml/Main.qml, qml/windowed/AppListView.qml
[【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【UI】全屏启动器应用组的背景模糊效果优化 #9374](https://github.com/linuxdeepin/developer-center/issues/9374)
[【deepin_V23_Release】【一般】【立即】【预发布测试】【DDE】【UI】窗口启动器应用分类的hover效果问题 #8807](https://github.com/linuxdeepin/developer-center/issues/8807)
[【deepin_V23_beta3】【严重】【立即】【预发布测试】【DDE】【launchpad】关闭窗口特效后，最大化切换最小化时，启动器没有最小化窗口显示 #6818](https://github.com/linuxdeepin/developer-center/issues/6818)
=> bump version to 0.7.5

qml/Main.qml
Set fixed size for fullscreen frame
Issue: https://github.com/linuxdeepin/developer-center/issues/9067
Log: Fix resizable fullscreen frame in latest kwin PR
=> fix: Fix resizable fullscreen frame in latest kwin PR

qml/FolderGridViewPopup.qml
Modify the color and position of the launcher application folder title
Issue: https://github.com/linuxdeepin/developer-center/issues/9446
=> fix: the launcher application folder title

launchercontroller.cpp, launchercontroller.h, qml/Main.qml
* 仅当 visible 为 true 时调用 requestActivate，调用时机不对导致 active 状态异常
* 切换模式后增加超时，1s 内 active 状态变更，只处理最后一次
Issues: linuxdeepin/developer-center#9567
=> fix: window is closed after switching mode

debian/changelog
Chanwqgelog:
* Insufficient transparency of the outer border (linuxdeepin/developer-center#8342)
* Can't input Chinese when opening the launcher (linuxdeepin/developer-center#8469)
* Cherry-pick fixes from 0.7.x maintenance branch
Log:
=> chore: release dde-launchpad 0.8.0

qml/windowed/FreeSortListView.qml
Support application groups when using the spacebar and return key
Issue: https://github.com/linuxdeepin/developer-center/issues/9737
=> fix: mini launcher can't open the appGroup by space or return key

qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml, qml/windowed/WindowedFrame.qml
小窗口启动器动画支持
Log:
------
主要注意点：
FolderGridViewPopup 的 popup 背景是个 `FloatingPanel`，提供了模糊功能。此模糊功能在当前状态下动画过程中以及结束后似乎无法得到和无动画时完全一致的渲染效果，推测可能是 dtk bug？ @18202781743 
简单的效果对比方式：
修改 `FolderGridViewPopup.qml` 第 333 行代码为 `blurMultiplier: root.enter.running ? 5.0 : 5.01`，通过更新 blurMultiplier 来触发一次 `FloatingPanel` 重绘，效果就正常了。
=> feat: windowed launcher app-folder animation

qml/FullscreenFrame.qml
修复全屏模式无法拖放图标的问题，由 218212824c3d8f 引入。
Log:
=> fix: not able to rearrange item in fullscreen mode

qml/Helper.qml
Reduce appitems row padding
Issue: https://github.com/linuxdeepin/developer-center/issues/9748 
Log:
=> fix: Frequently used app items will overlap search bar splitline

qml/FolderGridViewPopup.qml
Key events are filtered by upper droparea delegate, and need to be forwarded to inner IconItemDelegate.
Issue: https://github.com/linuxdeepin/developer-center/issues/9930
Log: Cannot open apps inside folders with keyboard
=> fix: Cannot open apps inside folders with keyboard

qml/FullscreenFrame.qml
鼠标释放前的位移动画。动画发生时实际已发生了model操作。
Log:
=> feat(UI): fullscreen item pre-drop arrangement animation

qml/Main.qml
When platform is xcb, set fixed size
Issue: https://github.com/linuxdeepin/developer-center/issues/9996
=> fix: display issues with fullscreen frame

CMakeLists.txt, debian/control, desktopintegration.cpp, desktopintegration.h, main.cpp, qml/FullscreenFrame.qml, qml/Main.qml, src/models/sortproxymodel.cpp, src/treelandintegration/CMakeLists.txt, src/treelandintegration/personalizationmanager.cpp, src/treelandintegration/personalizationmanager.h, src/treelandintegration/personalizationwindow.cpp, src/treelandintegration/personalizationwindow.h, src/treelandintegration/treeland-personalization-manager-v1.xml
通过 TreeLand 特性让合成器绘制全屏启动器的模糊背景。
Log:
=> feat: treeland window background for fullscreen frame

main.cpp
=> fix: personalize fullscreen mode instead of windowed mode

qml/windowed/FreeSortListView.qml, qml/windowed/WindowedFrame.qml
多个问题导致：
1. 文件夹的 20% 大小仍然比图标大，调到 10%
2. 之前起点是 item 的左上角，应当以图标中心为起点
3. 还需要将坐标进行一次映射
=> fix: windowed mode folder animation incorrect start point

dde-shell-wrapper/package/main.qml
Set the screen of the dock to the screen of the fullscreen frame
Issue: https://github.com/linuxdeepin/developer-center/issues/7188
=> fix: fullscreen frame follows the dock

qml/Main.qml
fullscreen frame grab keyboard When displayed
Issue: https://github.com/linuxdeepin/developer-center/issues/10224
=> fix: fullscreen frame can't get keyboard focus

.reuse/dep5, CMakeLists.txt, desktopintegration.cpp, dist/org.deepin.dde.shell.launchpad.appdata.xml, docs/DConfig.md, src/models/CMakeLists.txt, src/models/appsmodel.cpp, src/models/categorizedsortproxymodel.cpp, src/models/frequentlyusedproxymodel.cpp, src/models/org.deepin.ds.launchpad.json
纠正应用组件 ID 名称。
Log:
Influnce: 不再兼容之前的 dde-launchpad 配置文件
---------------------
关联：
- https://github.com/linuxdeepin/dde-launchpad/pull/383 （本 PR）
- https://github.com/linuxdeepin/dde-shell/pull/658
- https://github.com/linuxdeepin/dde-tray-loader/pull/120
- https://github.com/linuxdeepin/deepin-osconfig/pull/7 （可以先合入，不影响测试）
若未注明，均需先确认无问题再合入。
=> fix!: correct app id used by DConfig

qml/Main.qml
Launchpad should be displayed in full screen under wayland
Log:
=> feat: set fullscreen window ignore exclusive areas

qml/FolderGridViewPopup.qml
as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10157
=> fix: appList group popup text cannot be seen clearly in dark mode

qml/FolderGridViewPopup.qml
The height calculation is incorrect for '?:' operator having a lower priority than '+', which results in no title height added when cs is an even number.
Issue:
https://github.com/linuxdeepin/developer-center/issues/10021 https://github.com/linuxdeepin/developer-center/issues/10027 https://github.com/linuxdeepin/developer-center/issues/10320 Log: Correct application group popup height
=> fix: Correct application group popup height

src/treelandintegration/personalizationmanager.cpp
由于 TreeLand 计划更新协议，暂时移除相关调用。
Log:
=> chore: temporary disable treeland integration

qml/FullscreenFrame.qml
Fix the alignment of the launcher indicator
Issue: https://github.com/linuxdeepin/developer-center/issues/9993
=> fix: the fullscreen launcher indicator is not aligned

qml/GridViewContainer.qml, qml/windowed/GridViewContainer.qml
Limit the interval between repeated clicks
Issue: https://github.com/linuxdeepin/developer-center/issues/10481
=> fix: gridView tab switched too quickly

qml/FullscreenFrame.qml
searchEdit and exitFullscreenBtn need to be disabled after opening the app group
Issue: https://github.com/linuxdeepin/developer-center/issues/10255
=> fix: Update button status after opening app group

qml/IconItemDelegate.qml
give the max sourceSize and use scale
Issue: https://github.com/linuxdeepin/developer-center/issues/10456
=> fix: the fullscreen launcher icon flashes when resizing the dock size

qml/Helper.qml, qml/windowed/FreeSortListView.qml, qml/windowed/ItemBackground.qml
same color as the hover
Log: update the color
Bug: https://pms.uniontech.com/bug-view-271431.html
=> fix: update the color of a darg-and-drop in FreeSortList

qml/FullscreenFrame.qml
if the property is later assigned a static value from a JavaScript statement, the binding will be removed. 
If you need to assign, please rebind the property after assigning.
Issue: https://pms.uniontech.com/bug-view-272715.html
=> fix: failed to switch pages by clicking indicator button

qml/FullscreenFrame.qml
Determine the position of the focus by using the left or right key pressed
Log: the focus position
Bug: https://pms.uniontech.com/bug-view-272993.html
=> fix: the focus position is wrong when turning the page

qml/FullscreenFrame.qml
Bug: https://pms.uniontech.com/bug-view-270945.html
Log: Disable itemMoveTransition when switching to FullscreenFrame
=> feat: Disable itemMoveTransition when switching to FullscreenFrame

CMakeLists.txt, qml/FullscreenFrame.qml, shell-launcher-applet/CMakeLists.txt, shell-launcher-applet/launcheritem.cpp, shell-launcher-applet/package/launcheritem.qml
修复多个初版移植到 dde-shell 后引入的问题，包括：
- liblaunchpad 未安装（追加 install 并更改 target 名称）
- 全屏启动器无模糊版背景（补充注册 imageprovider）
- 全屏启动器上下滚轮无法翻页（补充缺失的辅助函数）
- 优化x11下全屏模糊背景的速度与内存占用（减小图片 sourcesize）
Log:
=> fix: various issue after initial port to dde-shell

shell-launcher-applet/package/launcheritem.qml
当小窗口启动器的 Popup 被隐藏时，更新 LauncherController 的状态，避免
下次按下 Meta 或点击启动器图标时无法使启动器重新显示出来。
Log:
=> fix: update controller visible state when windowed frame focus out

desktopintegration.cpp, desktopintegration.h
支持使用 AppStream 的自定义字段（`DDE:is_dummy_package`）声明虚拟占位包。
暂时没有 UI 实现，UI 相关的行为放到另外的提交中做。
Log:
=> feat: API to check if a package is dummy package

qml/windowed/FreeSortListView.qml, src/models/freesortproxymodel.cpp, src/models/freesortproxymodel.h, src/models/multipagesortfilterproxymodel.cpp, src/models/sortproxymodel.h
自由排序模式支持拖放动画（暂无拖拽过程中实时动画）
Log:
=> feat: support freeform-sort drop animation

qml/FullscreenFrame.qml, qml/IconItemDelegate.qml, qml/windowed/IconItemDelegate.qml
避免 hover 时由 ToolButton 导致的放大动效。
Log:
=> fix: avoid hover animation for grid items

qml/FullscreenFrame.qml
Bug: https://pms.uniontech.com/bug-view-277793.html
Log: Hide pageindicator when only one app page exists
=> feat: Hide pageindicator when only one app page exists

CMakeLists.txt, qml/DummyAppItemMenu.qml, qml/Main.qml, translations/dde-launchpad.ts, translations/dde-launchpad_az.ts, translations/dde-launchpad_bo.ts, translations/dde-launchpad_ca.ts, translations/dde-launchpad_es.ts, translations/dde-launchpad_fi.ts, translations/dde-launchpad_fr.ts, translations/dde-launchpad_hu.ts, translations/dde-launchpad_it.ts, translations/dde-launchpad_ja.ts, translations/dde-launchpad_ko.ts, translations/dde-launchpad_nb_NO.ts, translations/dde-launchpad_pl.ts, translations/dde-launchpad_pt_BR.ts, translations/dde-launchpad_ru.ts, translations/dde-launchpad_uk.ts, translations/dde-launchpad_zh_CN.ts, translations/dde-launchpad_zh_HK.ts, translations/dde-launchpad_zh_TW.ts
为占位包实现了仅有“安装”和“移除”的右键菜单。
cherry-pick 到维护分支并建立了对应的翻译条目。
Log: 为占位应用图标提供了简单版本的右键菜单。
=> feat: special context menu for dummy apps

qml/FolderGridViewPopup.qml, qml/FullscreenFrame.qml, qml/Helper.qml, qml/windowed/FreeSortListView.qml
对于将应用拖拽到Dock上固定的场景使用正确的MIME数据，并在不允许某应用固定到Dock上时不加入此MIME数据，以阻止Dock接受拖拽事件。此提交是占位包需求遗留问题的修复。
此PR目标为维护分支，与 linuxdeepin/dde-shell#818 互相依赖。
Log:
Bug: https://pms.uniontech.com/bug-view-279155.html
=> fix: use proper dock DnD MIME data

qml/AppItemMenu.qml, qml/DummyAppItemMenu.qml
Somehow, the Menu QML document doesn't mention the common margin option per directions.
Bug: https://pms.uniontech.com/bug-view-277989.html
Log: Set menu margin according to dock location
=> fix: Set menu margin according to dock location

qml/windowed/SearchResultView.qml
修复 Qt 6.8 下，小窗口启动器搜索结果视图对齐不正确的问题。
Log:
=> fix: windowed mode search result has incorrect alignment

debian/changelog
=> chore: release dde-launchpad 1.99.0 as alpha testing version

src/ddeintegration/appearance.cpp
Secondary monitor backgrounds were not included.
Bug: https://pms.uniontech.com/bug-view-279127.html
Log: Launchpad blurry background will never adapt to secondary monitor
=> fix: Launchpad blurry background will never adapt to secondary monitor

src/ddeintegration/appearance.cpp
QJsonDocument::object get a value object instead of a reference/pointer
log: as title
=> fix: launchpad crash at josn2value

debian/changelog
* support most areas apps drop to dock (PMS-285139)
* fix some strings on windowed launcher mode not translated (PMS-287975, PMS-287083, PMS-289493)
* update translations
Log:
=> chore: release dde-launchpad 1.99.2

qml/windowed/IconItemDelegate.qml
不可排序区域的图标拖拽功能添加的 DragHandler 导致 Button 的 click 被抢，导致只有图标外的区域的点击才有效。此修复选择了和全屏启动器相同的方案处理此问题，即另加一个 TapHandler 来处理点击事件。
Log:
=> fix: FrequentlyUsedView and RecentlyInstalledView icons not-clickable

shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_zh_CN.ts
任务栏上的启动器图标 hover tooltip 未提供翻译，此提交追加了相应翻译
PMS: BUG-278083
Log:
=> fix: add missing translation for launcher item tooltip

qml/windowed/FreeSortListView.qml
当鼠标释放拖拽时即停止滚动。之前因为 attached property 所设对象不对所以没有生效（可能是曾有过层级关系调整导致的）。
Log:
=> fix: stop freefrom sort view scrolling when drag finished

shell-launcher-applet/package/launcheritem.qml
x11下连续点启动器，应该可以正常的隐藏和显示
treeland点击快捷面板再点击启动器，启动器可以正常的显示
使用taphandler时都不行
=> fix: x11 launchpad can not hide

debian/changelog
* Show autostart icons for items in freeform-sort view
* Fix icons in some view are not clickable
* Add missing translation for launchpad icon on taskbar area
* Stop scrolling when freeform-sort view item drag finished
* Update tooltip delay time
* Fix x11 launchpad cannot hide
Log:
=> chore: release dde-launchpad 1.99.3

shell-launcher-applet/package/launcheritem.qml
Avoiding showing app organizating animation.
pms: BUG-286727
Log: Hide launchpad window as soon as launching Apps
=> fix: Hide launchpad window as soon as launching Apps

qml/windowed/AppListView.qml
修复分类列表模式的项目hover背景不显示的问题。
注意：当前dtkdeclarative存在问题，拖拽并释放后会导致hover残留，需要从dtkdeclarative一侧修复。
=> fix: hover background for category list view items

qml/windowed/SearchResultView.qml
Modify the recommended size of GridViewContainer
pms: Bug-291293
=> fix: the search results are displayed in the middle

src/models/appsmodel.cpp, src/models/appsmodel.h, src/models/searchfilterproxymodel.cpp
dtk::core::pinyin() returns all polyphonic characters, but it's
not used in transliterated.
We use all polyphonic characters to match searchPattern instead of
first word.
pms: BUG-288487
=> fix: can't search polyphonic characters

debian/changelog
Changelog:
* fix: fullscreen launcher should follow dock screen (Bug-300309)
Log:
=> chore: bump version to 1.99.7

qml/windowed/FreeSortListView.qml
修正部分场景下,拖拽导致的列表视图滚动无法被停止的问题.
PMS: BUG-303553
Log:
=> fix: cannot stop scrolling after drop in some cases

debian/changelog
Changelog:
* i18n: Updates for project Deepin Desktop Environment
* fix: item delegate margin not working in AppListView (Bug-300939)
* fix: cannot stop scrolling after drop in some cases (Bug-303553)
Log:
=> chore: release dde-launchpad 1.99.8

debian/changelog
Changelog:
* fix: assign fullscreen frame screen on init completed (Bug-300309)
=> chore: release dde-launchpad 1.99.9

qml/FolderGridViewPopup.qml
it's exist in windowed Mode,
according UI designer, selectedTextColor is white whether it's
in windowed Mode or full Mode.
pms: BUG-301103
=> fix: incorrect selectedTextColor for folderPopup

debian/changelog
Changelog:
* fix: incorrect selectedTextColor for folderPopup (Bug-301103)
* fix: correct category name for Games (Bug-289127)
Log:
=> chore: release dde-launchpad 1.99.10

qml/FullscreenFrame.qml, qml/GridViewContainer.qml
Also fix bug, when first open launchpad, open show focus in first app.
PMS-BUG-289119
=> feat: Added left and right button switching in full-screen mode.

qml/windowed/AlphabetCategoryPopup.qml, qml/windowed/AppListView.qml, qml/windowed/GridViewContainer.qml
=> feat: add focus with AlphabetCategory when change to another word.

shell-launcher-applet/package/launcheritem.qml, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_az.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_bo.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_ca.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_es.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_fi.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_fr.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_hu.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_it.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_ja.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_ko.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_nb_NO.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_pl.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_pt_BR.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_ru.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_uk.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_zh_CN.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_zh_HK.ts, shell-launcher-applet/translations/org.deepin.ds.dock.launcherapplet_zh_TW.ts
Changed the confirmation dialog button text from "Uninstall" to "Confirm" across all translation files to better reflect the action being confirmed rather than specifically uninstalling Reduced bottom margin from 20 to 10 in launcheritem.qml for better visual spacing in the dialog layout
Updated multiple translation files with proper XML formatting and consistent translation tags
This change improves user interface consistency and makes the confirmation action more generic for various operations
fix: 更新确认对话框按钮文本和布局
将所有翻译文件中的确认对话框按钮文本从"卸载"改为"确认"，以更好地反映确认
操作而非特定卸载行为
在launcheritem.qml中将底部边距从20减少到10，以改善对话框布局的视觉间距
更新多个翻译文件，采用正确的XML格式和一致的翻译标签
此更改提高了用户界面的一致性，并使确认操作更通用，适用于各种操作
Pms: BUG-324669
=> fix: update confirmation dialog button text and layout
